Repository nexodus-io/nexodus, pull requests merged in 2023-06, with the labels that each got.

#1106 mergify: Add a label when changes are requested on a PR
  .github/mergify.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1109 fix: store the kc admin password for the qa/prod deployments in a sealed secret
  deploy/nexodus/base/auth/kustomization.yaml
  deploy/nexodus/overlays/dev/kustomization.yaml
  deploy/nexodus/overlays/released/auth-sealed-secret.yaml
  deploy/nexodus/overlays/released/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1110 Adds some envoy graph to monitor the Envoy Active Requests and the Envoy Response Codes.
  deploy/nexodus-monitoring/base/grafana/apiserver-dashboard.yaml
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#973 Initial network policy PR
  cmd/nexctl/device.go
  cmd/nexctl/main.go
  cmd/nexctl/organization.go
  cmd/nexctl/security_group.go
  deploy/nexodus/base/apiserver/deployment.yaml
  deploy/nexodus/base/apiserver/kustomization.yaml
  deploy/nexodus/overlays/dev/kustomization.yaml
  docs/user-guide/security-groups.md
  integration-tests/features/device-api.feature
  integration-tests/features/feature-flags-api.feature
  integration-tests/features/organization-api.feature
  integration-tests/helper_test.go
  integration-tests/security_group_test.go
  integration-tests/util_test.go
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_security_group.go
  internal/api/public/client.go
  internal/api/public/model_models_add_device.go
  internal/api/public/model_models_add_organization.go
  internal/api/public/model_models_add_security_group.go
  internal/api/public/model_models_device.go
  internal/api/public/model_models_organization.go
  internal/api/public/model_models_security_group.go
  internal/api/public/model_models_security_rule.go
  internal/api/public/model_models_update_security_group.go
  internal/api/public/model_models_user.go
  internal/database/database.go
  internal/database/migration_20230428_0000/20230428-0000.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/fflags/fflags.go
  internal/handlers/device.go
  internal/handlers/organization.go
  internal/handlers/security_group.go
  internal/handlers/security_group_test.go
  internal/handlers/user.go
  internal/models/device.go
  internal/models/organization.go
  internal/models/security_group.go
  internal/models/user.go
  internal/nexodus/nexodus.go
  internal/nexodus/policy_darwin.go
  internal/nexodus/policy_linux.go
  internal/nexodus/policy_windows.go
  internal/nexodus/wg_deploy.go
  internal/routers/routers.go
  internal/routers/token.rego
Labels: has-design, has-docs, has-tests, changes-requested

#1122 Add bash autocompletion for nexctl and nexd
  Makefile
  cmd/nexctl/main.go
  cmd/nexd/main.go
  contrib/bash_autocomplete
  contrib/rpm/nexodus.spec.in
  docs/user-guide/agent.md
Labels: no-design-required, has-docs, no-tests-required

#1133 e2e: Add additional validation to nft list output
  integration-tests/security_group_test.go
Labels: no-design-required, no-docs-required, has-tests

#1119 mergify: Drop use of changes-requested label
  .github/mergify.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1138 Publish aarch64 rpms for Fedora and CentOS Stream
  .github/workflows/deploy.yml
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1118 nexd: Allow nexd to change peer configs
  internal/nexodus/nexodus.go
  internal/nexodus/wg_peers.go
Labels: no-design-required, no-docs-required, no-tests-required

#1134 nexd: Adjust security group reconciliation
  internal/nexodus/nexodus.go
  internal/nexodus/wg_deploy.go
Labels: no-design-required, no-docs-required, no-tests-required

#1140 Change no security group supoport for non-linux to informational
  internal/nexodus/nexodus.go
Labels: has-design, has-docs, has-tests

#1137 apiserver: Returning 409 conflict instead of 500 when creating organi…
  integration-tests/features/organization-api.feature
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/organization.go
Labels: no-design-required, has-docs, has-tests

#1156 fix SRPM variable name in Makefile
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1155 Ignore security groups in device reconcile
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#1163 Accept empty inbound/outbound SG rules
  internal/handlers/security_group.go
Labels: no-design-required, no-docs-required, no-tests-required

#1161 nexd: Add bash tab completion to container image
  Containerfile.nexd
Labels: no-design-required, no-docs-required, no-tests-required

#1158 proxy: support simple client-side load balancing for proxy mode
  cmd/nexd/main.go
  docs/user-guide/nexd-proxy.md
  go.mod
  hack/udpong/udpong.go
  integration-tests/helper_test.go
  integration-tests/proxy_test.go
  internal/nexodus/ctlserver.go
  internal/nexodus/nexodus.go
  internal/nexodus/proxyrule.go
  internal/nexodus/userspace_proxy.go
Labels: no-design-required, has-docs, has-tests

#1166 added custom zap logger config
  cmd/nexd/main.go
Labels: no-design-required, no-docs-required, no-tests-required

#1167 Add an additional fail parameter for QA.
  .github/workflows/qa-dev.yml
  .github/workflows/qa-scale-containers.yml
  .github/workflows/qa-scale.yml
Labels: has-design, has-docs, has-tests

#1169 rpm: Rename rpm build artifacts
  .github/workflows/build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1178 hack: Add kubectl to install-tools.sh
  hack/install-tools.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1181 nexd: Don't attempt security groups in proxy mode
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#1190 renames ax to nx on all the /internal/nexodus/nexodus*.go files
  internal/nexodus/nexodus.go
  internal/nexodus/nexodus_darwin.go
  internal/nexodus/nexodus_linux.go
  internal/nexodus/nexodus_userspace.go
  internal/nexodus/nexodus_windows.go
Labels: no-design-required, no-docs-required, no-tests-required

#1189 CONTRIBUTING.md: Add link to pull-requests doc
  CONTRIBUTING.md
Labels: no-design-required, has-docs, no-tests-required

#1192 Add v6 support for nexd peers ping
  cmd/nexctl/connectivity.go
  cmd/nexctl/local_unix.go
  internal/nexodus/ctlconnectivty.go
  internal/nexodus/keepalive.go
  ops/ansible/aws/validate-connectivity/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1193 nexctl: Trim down peers list output
  cmd/nexctl/local_unix.go
  cmd/nexctl/peers.go
Labels: no-design-required, no-docs-required, no-tests-required

#1194 renames ax to nx in the receiver functions of internal/nexodus/keys*.go files
  internal/nexodus/keys.go
  internal/nexodus/keys_darwin.go
  internal/nexodus/keys_linux.go
  internal/nexodus/keys_windows.go
Labels: no-design-required, no-docs-required, no-tests-required

#1198 Add a full and partial display for columns in nexctl device lists
  cmd/nexctl/device.go
  cmd/nexctl/main.go
Labels: no-design-required, no-docs-required, no-tests-required

#1200 change Apex to Nexodus in docs
  docs/index.md
Labels: no-design-required, has-docs, no-tests-required

#1183 apiserver: Move creating a user/organization in a transaction block
  internal/handlers/organization.go
  internal/handlers/security_group.go
  internal/handlers/user.go
Labels: no-design-required, no-docs-required, no-tests-required

#1208 Create organization sg transaction
  internal/handlers/organization.go
  internal/handlers/user.go
Labels: no-design-required, no-docs-required, no-tests-required

#1212 updating cli org-id flag to organization-id
  cmd/nexctl/main.go
  cmd/nexd/main.go
  docs/user-guide/agent.md
  integration-tests/integration_test.go
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#1007 Use a shared ipam namespace by default.
  cmd/nexctl/main.go
  cmd/nexctl/organization.go
  docs/development/design/nexlink.md
  docs/user-guide/discovery-and-relay.md
  docs/user-guide/nexd-proxy.md
  integration-tests/features/organization-api.feature
  integration-tests/helper_test.go
  integration-tests/integration_test.go
  integration-tests/proxy_test.go
  integration-tests/security_group_test.go
  internal/api/public/model_models_add_organization.go
  internal/api/public/model_models_organization.go
  internal/database/database.go
  internal/database/migration_20230509_0000/20230509-0000.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/device.go
  internal/handlers/handlers_test.go
  internal/handlers/organization.go
  internal/handlers/organization_test.go
  internal/handlers/user.go
  internal/models/organization.go
  ops/ansible/aws/vars.yml
  ops/ansible/azure/vars.yml
  ops/ansible/gcp/vars.yml
Labels: has-design, has-docs, has-tests

#1210 Parameterize the qa deployment timeout with a dispatch option
  .github/workflows/qa-scale-containers.yml
  .github/workflows/qa-scale.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1215 Fix e2e org-id/organization-id
  integration-tests/integration_test.go
Labels: no-design-required, no-docs-required, no-tests-required

#1218 Add a debug pause in the playbooks as specified by the action dispatch
  docs/development/scale-testing.md
  ops/ansible/aws/qa/validate-connectivity-qa-containers/tasks/main.yml
  ops/ansible/aws/validate-connectivity/tasks/main.yml
Labels: no-design-required, has-docs, no-tests-required

#1214 nexd: configure the service-url using a flag
  cmd/nexd/main.go
  docs/deployment/nexodus-service.md
  docs/development/design/userspace-mode.md
  docs/quickstart.md
  docs/user-guide/agent.md
  docs/user-guide/discovery-and-relay.md
  docs/user-guide/nexd-proxy.md
  docs/user-guide/scenarios/nexd-proxy-in-kube.md
  hack/update-ca.sh
  integration-tests/helper_test.go
  internal/handlers/organization.go
Labels: no-design-required, has-docs, has-tests

#1219 Device Metadata API
  Makefile
  cmd/nexctl/device_metadata.go
  cmd/nexctl/main.go
  docs/development/design/device-metadata.md
  integration-tests/features/device-metadata-api.feature
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_device_metadata_custom.go
  internal/api/public/api_devices.go
  internal/api/public/model_models_device_metadata.go
  internal/database/database.go
  internal/database/migration_20230610_0000/20230610-0000.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/device_metadata.go
  internal/handlers/stream.go
  internal/models/device_metadata.go
  internal/routers/routers.go
Labels: has-design, no-docs-required, has-tests

#1223 Add debian build configurations for a PPA and deb packaging
  contrib/debian/README.md
  contrib/debian/changefile
  contrib/debian/control
  contrib/debian/nexodus.conf
  contrib/debian/nexodus.service
  contrib/debian/rules
  contrib/debian/source/format
Labels: no-design-required, has-docs, no-tests-required

#1172 docs: Propose API support for device metadata
  docs/development/design/device-metadata.md
Labels: enhancement, apiserver, needs-rebase, has-design, no-docs-required, no-tests-required

#1220 nexd: Optionally build with pprof support
  Containerfile.nexd
  Makefile
  cmd/nexd/main.go
  cmd/nexd/pprof_disabled.go
  cmd/nexd/pprof_enabled.go
  docs/development/debugging.md
Labels: no-design-required, has-docs, no-tests-required

#1232 apiserver cleanup: Reduced code duplication in device watch handler
  internal/handlers/device_metadata.go
  internal/handlers/organization.go
  internal/handlers/stream.go
Labels: no-design-required, no-docs-required, has-tests

#1235 Remove legacy organization-hub from nexctl
  cmd/nexctl/main.go
  cmd/nexctl/organization.go
Labels: no-design-required, no-docs-required, no-tests-required

#1211 Switching device registration log for newly register device and re-connecting devices
  internal/nexodus/join.go
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required
