Repository nexodus-io/nexodus, pull requests merged in 2023-08, with the labels that each got.

#1302 Scale qa adjustments, variables and qa-container action fix
  hack/e2e-scripts/qa-container-scale.sh
  ops/ansible/aws/qa/validate-connectivity-qa-containers/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1301 add logging to qa script per container
  hack/e2e-scripts/qa-container-scale.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1304 Update playbooks with new state storage scheme
  ops/ansible/aws/deploy-mesh/tasks/main.yml
  ops/ansible/aws/deploy-relay/tasks/main.yml
Labels: ci, no-design-required, no-docs-required, no-tests-required

#1303 Update deployment yamls to
  deploy/nexodus/base/apiproxy/deployment.yaml
  deploy/nexodus/base/apiproxy/kustomization.yaml
  deploy/nexodus/overlays/dev/kustomization.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1306 ui: Override minimist to >=0.2.4
  ui/package-lock.json
  ui/package.json
Labels: no-design-required, no-docs-required, no-tests-required

#1307 apiserver: add a `ipam` sub command to clear/rebuild the ipam address…
  cmd/apiserver/main.go
  internal/ipam/cmd/clear.go
  internal/ipam/cmd/rebuild.go
  internal/ipam/ipam.go
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1311 apiserver: add debug logging to the ipam clear command.
  cmd/apiserver/main.go
  internal/ipam/cmd/clear.go
Labels: no-design-required, no-docs-required, no-tests-required

#1308 go: Update net to v0.13.0
  go.mod
  go.sum
Labels: no-design-required, no-docs-required, no-tests-required

#1313 Use some slightly better defaults for the ipam cli flags.
  cmd/apiserver/main.go
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1309 ui: switch to vite-plugin-favicons-inject
  ui/package-lock.json
  ui/package.json
  ui/vite.config.ts
Labels: no-design-required, no-docs-required, no-tests-required

#1320 fix: `make clear-db` and `make recreate-db`
  Makefile
  deploy/nexodus/base/redis/redis-statefulset.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1328 podman support for kind qa scale tests
  docs/development/scale-testing.md
  hack/e2e-scripts/qa-kind-container-scale.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1329 Enable cgo in e2e make
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1321 Resolve the nexctl peer list panic
  cmd/nexctl/peers.go
  integration-tests/integration_test.go
Labels: no-design-required, no-docs-required, no-tests-required

#1336 Resolve react dependency for @testing-library/jest-dom
  ui/package.json
  ui/src/App.test.tsx
  ui/tsconfig.json
Labels: no-design-required, no-docs-required, no-tests-required

#1338 Don’t compile in the kstore code introduced in dd822f7
  Makefile
  cmd/nexd/main.go
  integration-tests/helper_test.go
  integration-tests/kube_test.go
  internal/state/kstore/kstore.go
  internal/state/kstore/kstore_off.go
Labels: no-design-required, no-docs-required, no-tests-required

#1312 Nexodus manifest files for playground namespace
  deploy/nexodus/overlays/playground/files/nexodus.json
  deploy/nexodus/overlays/playground/files/promtail.yaml
  deploy/nexodus/overlays/playground/issuer.yaml
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/playground/sealed-secret.yaml
  deploy/nexodus/overlays/playground/serviceaccount.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1341 Override the limitador limits for playground deployment
  deploy/nexodus/overlays/playground/files/limits.yaml
  deploy/nexodus/overlays/playground/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1340 Update scale script to
  hack/e2e-scripts/qa-container-scale.sh
  hack/e2e-scripts/qa-kind-container-scale.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1342 Add wireguard userspace tools to the nexd image
  Containerfile.dev
  Containerfile.nexd
Labels: no-design-required, no-docs-required, no-tests-required

#1344 Added windows instructions in the docs quick start
  docs/quickstart.md
  docs/user-guide/network-routers.md
Labels: no-design-required, has-docs, no-tests-required

#1346 Support scripts for scale testing
  .gitignore
  hack/e2e-scripts/scale/check-connectivity.sh
  hack/e2e-scripts/scale/check-errors.sh
  hack/e2e-scripts/scale/qa-container-scale.sh
  hack/e2e-scripts/scale/qa-kind-container-scale.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1347 Automate the debian packaging and PPA repo push
  .github/workflows/ppa-build.yml
  contrib/debian/changelog
  docs/quickstart.md
Labels: no-design-required, has-docs, no-tests-required

#1355 Fix escaping in PPA/Deb build workflow
  .github/workflows/ppa-build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1357 Fix kctool location
  hack/e2e-scripts/scale/qa-container-scale.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1345 Cleaning up windows logging and routing
  internal/nexodus/nexodus.go
  internal/nexodus/nexodus_windows.go
  internal/nexodus/route_windows.go
  internal/nexodus/utils_windows.go
  internal/stun/client.go
Labels: no-design-required, no-docs-required, no-tests-required

#1356 feat: enable the kstore implementation via subprocess IPC.
  Containerfile.nexd
  Makefile
  cmd/nexd-kstore/main.go
  cmd/nexd/main.go
  go.mod
  go.sum
  integration-tests/kube_test.go
  internal/state/fstore/fstore.go
  internal/state/ipc/client.go
  internal/state/ipc/server.go
  internal/state/kstore/kstore.go
  internal/state/kstore/kstore_ipc.go
  internal/state/kstore/kstore_off.go
  internal/state/state.go
Labels: no-design-required, no-docs-required, has-tests

#1361 docs: Add dark mode quickstart overview diagram
  docs/images/quickstart-overview-1-dark.png
  docs/quickstart.md
Labels: no-design-required, no-docs-required, no-tests-required
