Repository nexodus-io/nexodus, pull requests merged in 2023-09, with the labels that each got.

#1364 Take number of orgs in the scale script to create multiple orgs.
  hack/e2e-scripts/scale/check-connectivity.sh
  hack/e2e-scripts/scale/check-errors.sh
  hack/e2e-scripts/scale/qa-container-scale.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1365 Update scale testing docs with script related changes
  docs/development/scale-testing.md
Labels: no-design-required, no-docs-required, no-tests-required

#1377 Add nftables to the ppa/deb dependancy
  contrib/debian/control
Labels: no-design-required, no-docs-required, no-tests-required

#1380 feat: support watching security groups.
  internal/api/public/api_security_group.go
  internal/api/public/api_security_group_custom.go
  internal/api/public/model_models_security_group.go
  internal/database/database.go
  internal/database/migration_20230907_0000/20230907-0000.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/security_group.go
  internal/models/security_group.go
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#1373 Add latency to nexd peers ping outputs
  cmd/nexctl/connectivity.go
  internal/nexodus/ctlconnectivty.go
  internal/nexodus/keepalive.go
Labels: no-design-required, no-docs-required, no-tests-required

#1363 More windows route logging cleanup
  internal/nexodus/route_windows.go
  internal/nexodus/utils_windows.go
Labels: no-design-required, no-docs-required, no-tests-required

#1027 Exit node design doc
  docs/development/design/exit-node.md
Labels: has-design, no-docs-required, no-tests-required

#1381 Fix qa-dev workflow build
  docs/deployment/nexodus-service.md
  hack/e2e-scripts/init-pr-e2e.sh
Labels: no-design-required, has-docs, no-tests-required

#1384 nexd: Fix peering health monitoring
  Containerfile.nexd
  cmd/nexd/main.go
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#1392 Remove legacy keys and locations
  integration-tests/integration_test.go
  internal/nexodus/keys.go
  internal/nexodus/nexodus.go
  internal/nexodus/utils_darwin.go
  internal/nexodus/utils_linux.go
  internal/nexodus/utils_windows.go
Labels: no-design-required, no-docs-required, no-tests-required

#1394 rpm: drop aarch64 rpm build for epel9
  .github/workflows/deploy.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1393 Add elevated privileges check at nexd runtime
  internal/nexodus/nexodus.go
  internal/nexodus/utils_darwin.go
  internal/nexodus/utils_linux.go
  internal/nexodus/utils_windows.go
Labels: no-design-required, no-docs-required, no-tests-required

#1395 Remove delete user from the UI
  cmd/nexctl/main.go
  ui/src/pages/Users.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1396 Bump node and buildx
  .github/workflows/deploy.yml
  Containerfile.frontend
Labels: no-design-required, no-docs-required, no-tests-required

#1397 Rollback vite-plugin-favicon-inject
  ui/package-lock.json
  ui/package.json
  ui/vite.config.ts
Labels: no-design-required, no-docs-required, no-tests-required

#1398 Add utility script to check nexd status of all the
  .gitignore
  hack/e2e-scripts/scale/check-connectivity.sh
  hack/e2e-scripts/scale/check-errors.sh
  hack/e2e-scripts/scale/check-nexd-status.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1358 Playground manifest configuration updates to support 10K devices
  deploy/nexodus/base/apiserver/deployment.yaml
  deploy/nexodus/base/auth/deployment.yaml
  deploy/nexodus/base/database/postgres.yaml
  deploy/nexodus/base/ipam/deployment.yaml
  deploy/nexodus/overlays/dev/kustomization.yaml
  deploy/nexodus/overlays/playground/files/envoy.yaml
  deploy/nexodus/overlays/playground/files/limits.yaml
  deploy/nexodus/overlays/playground/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1401 Scale related updates to qa manifests
  deploy/nexodus/overlays/qa/files/envoy.yaml
  deploy/nexodus/overlays/qa/files/limits.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1382 feat: implement an events endpoint that lets you watch multiple event types.
  go.mod
  integration-tests/features/events-api.feature
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_organizations.go
  internal/api/public/model_models_watch.go
  internal/api/public/model_models_watch_event.go
  internal/cucumber/http_request.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/events.go
  internal/handlers/security_group.go
  internal/handlers/stream.go
  internal/models/watch_event.go
  internal/routers/routers.go
  internal/signalbus/signalbus.go
Labels: no-design-required, no-docs-required, has-tests

#1399 Add nexd binaries with prod promotion
  .github/workflows/promote.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1391 Implements a shared informer API for nexd
  deploy/nexodus/base/apiproxy/deployment.yaml
  deploy/nexodus/base/apiproxy/files/envoy.yaml
  deploy/nexodus/base/apiproxy/ingress.yaml
  docs/development/design/watch-api.md
  integration-tests/api_test.go
  integration-tests/features/events-api.feature
  internal/api/public/api_devices_custom.go
  internal/api/public/api_organizations.go
  internal/api/public/api_organizations_custom.go
  internal/api/public/api_security_group_custom.go
  internal/api/public/model_models_watch.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/events.go
  internal/handlers/stream.go
  internal/models/watch_event.go
  internal/nexodus/nexodus.go
  internal/util/json.go
Labels: has-design, no-docs-required, has-tests

#1403 Separate oidc check auth into a seperate endpoint
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_auth.go
  internal/api/public/model_models_check_auth_response.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/routers/routers.go
  pkg/oidcagent/handlers.go
  pkg/oidcagent/models/models.go
  pkg/oidcagent/router.go
  ui/src/providers/AuthProvider.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1293 Add exit node client/server support
  cmd/nexctl/exit_node.go
  cmd/nexctl/local_unix.go
  cmd/nexd/main.go
  docs/images/exit-node-example-1.png
  docs/user-guide/exit-node.md
  integration-tests/routing_test.go
  integration-tests/security_group_test.go
  internal/nexodus/ctlconnectivty.go
  internal/nexodus/ctlexit.go
  internal/nexodus/ctlpeers.go
  internal/nexodus/ctlserver.go
  internal/nexodus/ctlserver_unix.go
  internal/nexodus/exit_client.go
  internal/nexodus/exit_node.go
  internal/nexodus/exit_origin.go
  internal/nexodus/nexodus.go
  internal/nexodus/nexodus_linux.go
  internal/nexodus/policy_darwin.go
  internal/nexodus/policy_windows.go
  internal/nexodus/route_darwin.go
  internal/nexodus/route_linux.go
  internal/nexodus/route_windows.go
  internal/nexodus/utils.go
  internal/nexodus/utils_darwin.go
  internal/nexodus/utils_linux.go
  internal/nexodus/utils_windows.go
Labels: has-design, has-docs, has-tests

#1411 Convert qa-dev init script to Ansible
  hack/e2e-scripts/aws-e2e-pr-build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1407 nexd: Refactor peering method choices
  internal/nexodus/wg_peers.go
Labels: no-design-required, no-docs-required, no-tests-required

#1412 Remove old qa-dev init scripts
  .github/workflows/qa-dev.yml
  hack/e2e-scripts/init-pr-e2e.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1413 Scale related updates to prod manifests files
  Makefile
  deploy/nexodus/components/limitador/kustomization.yaml
  deploy/nexodus/components/promtail/kustomization.yaml
  deploy/nexodus/overlays/dev/files/promtail.yaml
  deploy/nexodus/overlays/dev/kustomization.yaml
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/prod/files/envoy.yaml
  deploy/nexodus/overlays/prod/files/limits.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1414 Update playground/qa manifest to adopt changes from latest kustomize release
  Makefile
  deploy/nexodus/components/limitador/kustomization.yaml
  deploy/nexodus/components/promtail/kustomization.yaml
  deploy/nexodus/overlays/dev/files/promtail.yaml
  deploy/nexodus/overlays/dev/kustomization.yaml
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1424 Upgrade to latest sqlite version.
  go.mod
  go.sum
Labels: no-design-required, no-docs-required, no-tests-required

#1375 fix: #1374 add a watch cache reduce the number of queries needed to watch or device changes in large orgs.
  docs/development/design/watch-api.md
  integration-tests/features/device-metadata-api.feature
  integration-tests/features/organizations-devices-api.feature
  integration-tests/redis_fetch_manager_test.go
  internal/handlers/api.go
  internal/handlers/device_metadata.go
  internal/handlers/events.go
  internal/handlers/fetchmgr/basefm/base_fetch_manager.go
  internal/handlers/fetchmgr/envfm/envfm.go
  internal/handlers/fetchmgr/fetch_manager.go
  internal/handlers/fetchmgr/memfm/mem_fetch_manager.go
  internal/handlers/fetchmgr/memfm/mem_fetch_manager_test.go
  internal/handlers/fetchmgr/nonefm/envfm.go
  internal/handlers/fetchmgr/redisfm/redis_fetch_manager.go
  internal/handlers/fetchmgr/resource.go
  internal/handlers/fetchmgr/tests/fetchmgr.go
  internal/handlers/organization.go
  internal/handlers/security_group.go
  internal/handlers/stream.go
  internal/util/time.go
  internal/util/time_windows.go
Labels: has-design, no-docs-required, has-tests

#1423 Copy over the qa/prod envoy changes to the dev envoy config
  deploy/nexodus/base/apiproxy/files/envoy.yaml
  deploy/nexodus/overlays/playground/files/envoy.yaml
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/prod/files/envoy.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/files/envoy.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1427 fix: avoid ‘net/http: timeout awaiting response headers’ in nexd
  internal/handlers/events.go
Labels: no-design-required, no-docs-required, no-tests-required

#1434 ci(Mergify): configuration update
  .github/mergify.yml
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1430 localip: drop nexodus dependency
  hack/localip/main.go
Labels: no-design-required, no-docs-required, no-tests-required

#1428 feat: support building nexd and the apiserver with the go race detector
  Containerfile.apiserver
  Containerfile.nexd
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1429 systemd: Fix support for multiple nexd arguments
  contrib/debian/nexodus.conf
  contrib/debian/nexodus.service
  contrib/rpm/nexodus.service
  contrib/rpm/nexodus.sysconfig
Labels: no-design-required, no-docs-required, no-tests-required

#1433 fix: allow longer long polls on openshift.
  deploy/nexodus/base/apiproxy/ingress.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1425 fix: don’t use the gorm Scopes() method, it’s behavior is more complex than we realized.
  internal/handlers/device.go
  internal/handlers/device_metadata.go
  internal/handlers/events.go
  internal/handlers/handlers.go
  internal/handlers/invitations.go
  internal/handlers/organization.go
  internal/handlers/security_group.go
  internal/handlers/user.go
Labels: no-design-required, no-docs-required, no-tests-required

#1435 deploy: Enable apiserver debug in prod
  deploy/nexodus/overlays/prod/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1438 fix: the arm64 overlay to work with recent pgbouncer changes.
  deploy/nexodus/overlays/arm64/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1436 build(deps): bump gorm versions
  go.mod
  go.sum
  internal/database/errors.go
  internal/handlers/organization.go
Labels: no-design-required, no-docs-required, no-tests-required

#1437 build(deps): bump opentelemetry versions
  go.mod
  go.sum
Labels: no-design-required, no-docs-required, no-tests-required

#1440 Revert "deploy: Enable apiserver debug in prod"
  deploy/nexodus/overlays/prod/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1441 qa-dev: dump connectivity test info for all nodes
  .github/workflows/qa-dev.yml
  ops/ansible/aws/deploy-ec2-qa.yml
  ops/ansible/aws/qa/validate-connectivity-qa-containers/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1442 qa-dev: Fix globbing in workflow
  .github/workflows/qa-dev.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1443 feat: apiserver will now track a device’s online status
  integration-tests/api_test.go
  integration-tests/features/device-api.feature
  internal/api/public/api_organizations.go
  internal/api/public/api_organizations_custom.go
  internal/api/public/model_models_device.go
  internal/database/database.go
  internal/database/migration_20230921_0000/20230921-0000.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/api.go
  internal/handlers/events.go
  internal/handlers/fetchmgr/envfm/envfm.go
  internal/handlers/online_tracker.go
  internal/handlers/user.go
  internal/models/device.go
  internal/nexodus/nexodus.go
  internal/state/fstore/fstore.go
  internal/util/getenv.go
Labels: no-design-required, no-docs-required, no-tests-required

#1432 Security group CRUD support in the UI
  ui/package-lock.json
  ui/package.json
  ui/src/App.tsx
  ui/src/common/Api.tsx
  ui/src/common/IpHelpers.tsx
  ui/src/common/Notifications.tsx
  ui/src/layout/Menus.tsx
  ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
  ui/src/pages/SecurityGroups/SecurityGroupStructs.tsx
  ui/src/pages/SecurityGroups/SecurityGroupTable.tsx
  ui/src/pages/SecurityGroups/SecurityGroups.tsx
Labels: ui, no-design-required, no-docs-required, no-tests-required

#1447 qa-dev: Collect mesh connectivity from all nodes
  ops/ansible/aws/validate-connectivity/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1449 Add Static Favicons
  .excalidraw-ignore
  ui/index.html
  ui/package-lock.json
  ui/package.json
  ui/src/images/favicon/android-icon-144x144.png
  ui/src/images/favicon/android-icon-192x192.png
  ui/src/images/favicon/android-icon-36x36.png
  ui/src/images/favicon/android-icon-48x48.png
  ui/src/images/favicon/android-icon-72x72.png
  ui/src/images/favicon/android-icon-96x96.png
  ui/src/images/favicon/apple-icon-114x114.png
  ui/src/images/favicon/apple-icon-120x120.png
  ui/src/images/favicon/apple-icon-144x144.png
  ui/src/images/favicon/apple-icon-152x152.png
  ui/src/images/favicon/apple-icon-180x180.png
  ui/src/images/favicon/apple-icon-57x57.png
  ui/src/images/favicon/apple-icon-60x60.png
  ui/src/images/favicon/apple-icon-72x72.png
  ui/src/images/favicon/apple-icon-76x76.png
  ui/src/images/favicon/apple-icon-precomposed.png
  ui/src/images/favicon/apple-icon.png
  ui/src/images/favicon/browserconfig.xml
  ui/src/images/favicon/favicon-16x16.png
  ui/src/images/favicon/favicon-32x32.png
  ui/src/images/favicon/favicon-96x96.png
  ui/src/images/favicon/favicon.ico
  ui/src/images/favicon/manifest.json
  ui/src/images/favicon/ms-icon-144x144.png
  ui/src/images/favicon/ms-icon-150x150.png
  ui/src/images/favicon/ms-icon-310x310.png
  ui/src/images/favicon/ms-icon-70x70.png
  ui/vite.config.ts
Labels: no-design-required, no-docs-required, no-tests-required

#1448 Add the online health status to device list in nexctl
  cmd/nexctl/device.go
Labels: no-design-required, no-docs-required, no-tests-required

#1463 Add token refresh to client side web ui
  internal/api/public/api_auth.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/routers/routers.go
  pkg/oidcagent/handlers.go
  pkg/oidcagent/router.go
  ui/src/providers/AuthProvider.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1465 build: add the --context arg kubectl commands to avoid targeting the wrong cluster.
  Makefile
  cmd/nexd-kstore/main_off.go
Labels: no-design-required, no-docs-required, no-tests-required

#1466 apiserver: add the fetch manager configuration to the apiserver deployment
  deploy/nexodus/base/apiserver/deployment.yaml
  deploy/nexodus/base/apiserver/kustomization.yaml
  internal/handlers/events.go
  internal/handlers/fetchmgr/envfm/envfm.go
Labels: no-design-required, no-docs-required, no-tests-required

#1446 Add security groups validations for [ports,ip_ranges,protos]
  cmd/nexctl/security_group.go
  integration-tests/features/security-group-api.feature
  integration-tests/security_group_test.go
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_security_group.go
  internal/api/public/model_models_validation_error.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/security_group.go
  internal/handlers/security_group_test.go
  internal/util/ip_utils.go
  internal/util/ip_utils_test.go
Labels: no-design-required, no-docs-required, has-tests

#1471 Enable security groups feature for prod/qa/playground
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1469 Aliased predefined ports in sec group rules edit UI
  ui/package-lock.json
  ui/package.json
  ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1464 Add a health field to the device UI table
  ui/src/pages/Devices.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1473 apiserver: all internal server errors are now logged
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_devices.go
  internal/api/public/api_f_flag.go
  internal/api/public/api_invitation.go
  internal/api/public/api_organizations.go
  internal/api/public/api_security_group.go
  internal/api/public/api_users.go
  internal/api/public/model_models_internal_server_error.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/api.go
  internal/handlers/device.go
  internal/handlers/device_metadata.go
  internal/handlers/events.go
  internal/handlers/fflags.go
  internal/handlers/invitations.go
  internal/handlers/organization.go
  internal/handlers/security_group.go
  internal/handlers/user.go
  internal/models/error.go
  internal/routers/middleware.go
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1475 Revert token refresh
  deploy/nexodus/base/auth/files/nexodus.json
  deploy/nexodus/overlays/playground/files/nexodus.json
  deploy/nexodus/overlays/prod/files/nexodus.json
  deploy/nexodus/overlays/qa/files/nexodus.json
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_auth.go
  internal/api/public/model_models_check_auth_response.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/routers/routers.go
  pkg/oidcagent/handlers.go
  pkg/oidcagent/router.go
  ui/src/providers/AuthProvider.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1474 install-tools: Don't assume go bin dir exists
  hack/install-tools.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1476 Update prod manifest to adopt changes from latest kustomize release
  deploy/nexodus/overlays/prod/files/promtail.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1478 Makefile: don't assume .certs dir exists
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1480 qa-dev: Run connectivity check on all nodes
  ops/ansible/aws/deploy-ec2.yml
Labels: no-design-required, no-docs-required, no-tests-required
