Repository nexodus-io/nexodus, pull requests merged in 2023-05, with the labels that each got.

#948 mergify: Remove label requirements for dependabot changes
  .github/mergify.yml
Labels: no-design-required, no-docs-required, no-tests-required

#951 Added a bit to the kind quickstart doc
  MAINTAINERS.md
  docs/deployment/nexodus-service.md
Labels: no-design-required, has-docs, no-tests-required

#952 nexd: drop the requirement to install the wireguard tools.
  Containerfile.dev
  Containerfile.nexd
  Containerfile.test
  MAINTAINERS.md
  contrib/rpm/nexodus.spec.in
  docs/user-guide/scenarios/kubernetes-edge.md
  internal/cucumber/sql.go
  internal/nexodus/nexodus.go
  internal/nexodus/nexodus_darwin.go
  internal/nexodus/nexodus_linux.go
  internal/nexodus/utils_linux.go
  internal/util/Ignore_error.go
Labels: no-design-required, no-docs-required, no-tests-required

#959 nexd: Avoid segfault in error handling
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#956 nexd: Avoid duplicates in the newPeers list
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#957 Address proxy test reliability
  integration-tests/helper_test.go
  integration-tests/proxy_test.go
  internal/nexodus/userspace_proxy.go
Labels: no-design-required, no-docs-required, has-tests

#939 Makefile: add version target
  Makefile
Labels: no-design-required, has-docs, no-tests-required

#962 Handle token issues when swapping api-servers
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#961 e2e: Add logging to TestProxyInvalidConfig
  integration-tests/proxy_test.go
Labels: no-design-required, no-docs-required, has-tests

#964 e2e: Fix major flaw in TestProxyInvalidConfig
  integration-tests/proxy_test.go
Labels: no-design-required, no-docs-required, has-tests

#968 fix: test container log output had 8 bytes of binary junk before the …
  go.mod
  go.sum
  integration-tests/helper_test.go
  integration-tests/proxy_test.go
  integration-tests/util_test.go
Labels: no-design-required, no-docs-required, no-tests-required

#974 fix: null pointer panic in linux stun requets
  internal/nexodus/stun_linux.go
Labels: no-design-required, no-docs-required, no-tests-required

#975 bump: limitador version to the latest release.
  deploy/nexodus/components/limitador/limitador-deployment.yaml
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#969 rpm: Add centos-stream-9 support
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Makefile
  contrib/rpm/nexodus.spec.in
  docs/quickstart.md
  docs/user-guide/agent.md
Labels: no-design-required, has-docs, has-tests

#970 Remove resource limits for Deployments for Dev overlay
  deploy/nexodus/overlays/dev/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#971 fix: #787 Use a broader list of public STUN servers
  internal/nexodus/nexodus.go
  internal/nexodus/stun-servers.txt
  internal/nexodus/stun.go
  internal/nexodus/utils.go
Labels: no-design-required, no-docs-required, no-tests-required

#940 nexd: Fix connectivity probes for proxy mode
  integration-tests/proxy_test.go
  internal/nexodus/ctlconnectivty.go
  internal/nexodus/keepalive.go
Labels: no-design-required, no-docs-required, has-tests

#978 ci: Fix publish-rpm job
  .github/workflows/deploy.yml
Labels: no-design-required, no-docs-required, no-tests-required

#938 nexctl: Move connections command under nexd
  cmd/nexctl/local_unix.go
  cmd/nexctl/main.go
  integration-tests/proxy_test.go
  ops/ansible/aws/validate-connectivity/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#967 Fix minor issues in the fsm design doc
  docs/development/design/fsm.md
Labels: has-design, has-docs, no-tests-required

#979 Create Security Policy document
  SECURITY.md
Labels: no-design-required, has-docs, no-tests-required

#907 Scale testing tweaks
  ops/ansible/aws/deploy-mesh/tasks/main.yml
  ops/ansible/aws/deploy-relay/tasks/main.yml
  ops/ansible/aws/qa/qa-deploy-mesh/tasks/main.yml
  ops/ansible/aws/qa/qa-deploy-relay/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#980 docs: Drop mention of zones
  docs/user-guide/scenarios/kubernetes-edge.md
Labels: no-design-required, has-docs, no-tests-required

#889 doc: document the design around the watch api
  docs/development/design/watch-api.md
Labels: has-design, no-docs-required, no-tests-required

#996 rpm: Restart nexodus on package upgrade
  contrib/rpm/nexodus.spec.in
Labels: no-design-required, no-docs-required, has-tests

#997 Refactored WG Peers
  internal/nexodus/wg-peers.go
  internal/nexodus/wg_deploy.go
  internal/nexodus/wg_iface.go
  internal/nexodus/wg_peers.go
Labels: no-design-required, no-docs-required, no-tests-required

#1003 nexd: Move peer setup msg to debug
  internal/nexodus/wg_deploy.go
Labels: no-design-required, no-docs-required, no-tests-required

#1002 nexd: Drop back to using only google stun servers
  internal/nexodus/stun-servers.txt
Labels: no-design-required, no-docs-required, no-tests-required

#1004 nexd: Merge two device registration logs
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#999 rpm: Build centos-stream-9 rpms in the right root
  .github/workflows/deploy.yml
  Makefile
  contrib/rpm/nexodus.spec.in
Labels: no-design-required, no-docs-required, has-tests

#1005 Add logging for symmetric nat discovery
  internal/nexodus/nexodus.go
  internal/nexodus/stun_darwin.go
  internal/nexodus/stun_linux.go
  internal/nexodus/stun_windows.go
Labels: no-design-required, no-docs-required, no-tests-required

#1008 ci: Drop go-licenses job
  .github/workflows/build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1006 feat: e2e tests now run with a local stun server
  cmd/nexd/main.go
  integration-tests/helper_test.go
  integration-tests/main_test.go
  internal/nexodus/nexodus.go
  internal/nexodus/stun_windows.go
  internal/nexodus/utils.go
  internal/stun/client.go
  internal/stun/client_darwin.go
  internal/stun/client_linux.go
  internal/stun/client_windows.go
  internal/stun/server.go
  internal/stun/server_test.go
  internal/stun/stun-servers.txt
  internal/stun/stun.go
Labels: no-design-required, has-docs, has-tests

#937 Support running as a daemon on Mac
  contrib/mac/io.nexodus.nexd.plist
  docs/quickstart.md
  docs/user-guide/agent.md
Labels: no-design-required, has-docs, no-tests-required

#1010 Add square version of logo
  docs/assets/logo-square.png
Labels: no-design-required, no-docs-required, no-tests-required

#1009 Trim stun server list to prevent an empty string being returned
  internal/stun/stun.go
  internal/stun/stun_test.go
Labels: no-design-required, no-docs-required, no-tests-required

#1022 hack: Add tmux to nexd container
  Containerfile.nexd
  Makefile
  hack/update-ca.sh
Labels: no-design-required, has-docs, no-tests-required

#1026 deploy: Add MonitoringStack for ROSA
  deploy/nexodus-monitoring/overlays/rosa/kustomization.yaml
  deploy/nexodus-monitoring/overlays/rosa/monitoringstack.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1030 deploy: OpenShift Auth for Grafana / Promtail as a DaemonSet
  deploy/nexodus-monitoring/overlays/rosa/grafana-patch.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/kustomization.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/ocp-injected-certs.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/role.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/rolebinding.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/route.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/secret.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/serviceaccount.yaml
  deploy/nexodus-monitoring/overlays/rosa/kustomization.yaml
  deploy/nexodus-monitoring/overlays/rosa/monitoringstack.yaml
  deploy/nexodus/components/promtail/kustomization.yaml
  deploy/nexodus/components/promtail/promtail-daemonset.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1032 deploy/qa: Fix promtail namespace
  deploy/nexodus-monitoring/overlays/rosa/grafana/serviceaccount.yaml
  deploy/nexodus/overlays/qa/files/promtail.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1033 deploy/rosa: Make nexodus users grafana admins
  deploy/nexodus-monitoring/overlays/rosa/grafana-patch.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1034 deploy/rosa: Fix prometheus metrics
  deploy/nexodus-monitoring/base/kustomization.yaml
  deploy/nexodus-monitoring/overlays/dev/kustomization.yaml
  deploy/nexodus-monitoring/overlays/dev/prometheus-service.yaml
  deploy/nexodus-monitoring/overlays/rosa/kustomization.yaml
  deploy/nexodus-monitoring/overlays/rosa/monitoringstack.yaml
  deploy/nexodus-monitoring/overlays/rosa/prometheus-rbac.yaml
Labels: missing-docs-label, missing-design-label, missing-tests-label

#1035 grafana: Add a pretty chart for API requests
  deploy/nexodus-monitoring/base/grafana/apiserver-dashboard.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1039 .github: Remove context from docker-build-push action
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1041 deploy/rosa: Allow use of privileged scc
  .dockerignore
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1036 Remove redundant testcontainer teardown
  integration-tests/helper_test.go
  integration-tests/integration_test.go
Labels: no-design-required, no-docs-required, no-tests-required

#1042 docs: Document demo1 from the nexlink design
  docs/user-guide/scenarios/nexd-proxy-in-kube.md
Labels: has-design, has-docs, no-tests-required

#1029 Change the @Accepts field to @Accept in handler
  internal/api/public/api_devices.go
  internal/api/public/api_invitation.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/device.go
  internal/handlers/fflags.go
  internal/handlers/invitations.go
  internal/handlers/organization.go
  internal/handlers/user.go
Labels: no-design-required, no-docs-required, no-tests-required

#983 Check if the ChildPrefix is the same as the existing in UpdateDevice
  cmd/nexd/main.go
  integration-tests/integration_test.go
  internal/handlers/device.go
  internal/handlers/device_test.go
  internal/handlers/user.go
  internal/util/ip_utils.go
  internal/util/ip_utils_test.go
Labels: bug, no-design-required, no-docs-required, has-tests

#1031 convert the apiserver and frontend services to be headless
  deploy/nexodus/base/apiproxy/files/envoy.yaml
  deploy/nexodus/base/apiserver/service.yaml
  deploy/nexodus/base/frontend/service.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1048 docs: add proxy-in-kube demo 2 content
  docs/user-guide/scenarios/nexd-proxy-in-kube.md
Labels: has-design, has-docs, no-tests-required

#1047 docs: Update quickstart with docker instructions
  Containerfile.nexd
  docs/quickstart.md
  hack/update-ca.sh
Labels: no-design-required, has-docs, no-tests-required

#1051 Containerize QA
  .github/workflows/qa-scale-containers.yml
  ops/ansible/aws/ansible.cfg
  ops/ansible/aws/deploy-ec2-qa-containers.yml
  ops/ansible/aws/qa/qa-containers-deploy-mesh/tasks/main.yml
  ops/ansible/aws/qa/qa-deploy-relay/tasks/main.yml
  ops/ansible/aws/qa/validate-connectivity-qa-containers/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1064 docs/deployment: s/OperateFirst/ROSA/g and add grafana URL
  docs/deployment/deployment.md
Labels: no-design-required, has-docs, no-tests-required

#1065 docs: Document proxy-in-kube demo3
  docs/user-guide/scenarios/nexd-proxy-in-kube.md
Labels: has-design, has-docs, no-tests-required

#1062 e2e: Improve reliability of TestProxyInvalidConfig
  integration-tests/proxy_test.go
Labels: no-design-required, no-docs-required, has-tests

#1050 Add the ability to get wg information from the interface via nexctl
  cmd/nexctl/local_unix.go
  cmd/nexctl/peers.go
  docs/quickstart.md
  integration-tests/proxy_test.go
  internal/nexodus/ctlpeers.go
  ops/ansible/aws/validate-connectivity/tasks/main.yml
Labels: no-design-required, has-docs, no-tests-required

#1067 Add image-repositories env to the containerized scale qa
  .github/workflows/qa-scale-containers.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1070 nexd: Don't reconcile with stun when behind symmetric NAT
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1072 nexd: Remove some firstTime code for reconciliation
  internal/nexodus/nexodus.go
  internal/nexodus/nexodus_unix.go
  internal/nexodus/wg_deploy.go
  internal/nexodus/wg_iface.go
Labels: no-design-required, no-docs-required, has-tests

#1069 nexd: Support listing peers in proxy mode
  cmd/nexctl/peers.go
  internal/nexodus/ctlpeers.go
  internal/nexodus/dump.go
  internal/util/utils.go
Labels: no-design-required, no-docs-required, no-tests-required

#1045 Add a retry to failed STUN lookups on initilization
  cmd/nexd/main.go
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#953 Network policy design doc
  docs/development/design/security-groups.md
Labels: has-design, no-docs-required, no-tests-required

#1076 recreate-db would fail if the posgrescluster CRD is not installed
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1078 Updates to the readme
  README.md
Labels: no-design-required, no-docs-required, no-tests-required

#1077 Store peer configs as a map
  internal/nexodus/nexodus.go
  internal/nexodus/wg_deploy.go
  internal/nexodus/wg_peers.go
Labels: no-design-required, no-docs-required, no-tests-required

#1081 Resolve an issue with switching from symmetric to non-symmetric
  integration-tests/features/device-api.feature
  internal/handlers/device.go
  internal/models/device.go
Labels: no-design-required, no-docs-required, no-tests-required

#1083 Allow nexd to choose an organization to connect to
  cmd/nexd/main.go
  deploy/nexodus/base/apiserver/deployment.yaml
  deploy/nexodus/base/apiserver/kustomization.yaml
  deploy/nexodus/overlays/dev/kustomization.yaml
  docs/user-guide/agent.md
  integration-tests/integration_test.go
  internal/fflags/fflags.go
  internal/handlers/organization.go
  internal/handlers/organization_test.go
  internal/nexodus/join.go
  internal/nexodus/nexodus.go
  internal/nexodus/wg_peers.go
  ui/src/App.tsx
  ui/src/pages/Organizations.tsx
Labels: no-design-required, has-docs, has-tests

#1100 docs: Add nexctl usage docs
  contrib/nexctl-docs.sh
  docs/user-guide/nexctl.md
Labels: no-design-required, has-docs, no-tests-required

#1104 Remove the UI login background img
  ui/src/pages/Login.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1103 Use Material-UI theme for useTheme from @mui/material/styles
  ui/src/pages/Dashboard.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1098 nexd: Eliminiate a traversal of the device cache
  internal/nexodus/nexodus.go
  internal/nexodus/wg_peers.go
Labels: no-design-required, no-docs-required, no-tests-required
