Repository nexodus-io/nexodus, pull requests merged in 2023-04, with the labels that each got.

#793 ci: Speed up rpm builds in CI
  Makefile
Labels: ci, rpm

#902 feat: add `make k8s-lint` target and a `make k8s-crd-extract` target
  .github/workflows/build.yml
  Makefile
  hack/install-tools.sh
Labels: no-design-required, no-docs-required

#906 Remove install script
  contrib/nexodus-installer.sh
  docs/quickstart.md
  docs/user-guide/agent.md
Labels: no-design-required, has-docs

#908 fix: use the nexd-wireguard-go binary if it can be found on the path.
  internal/nexodus/nexodus.go
  internal/nexodus/nexodus_darwin.go
  internal/nexodus/utils_darwin.go
Labels: no-design-required, no-docs-required

#905 fix: the monitoring components still don’t work on qa, rollback recent changes.
  deploy/nexodus/overlays/released/kustomization.yaml
Labels: no-design-required, no-docs-required

#911 mergify: Give hints via labels about doc label requirements
  .github/mergify.yml
Labels: no-design-required, no-docs-required

#912 Add linting for GitHub actions workflows
  .github/workflows/actionlint.yml
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/qa-dev.yml
  .github/workflows/qa-scale.yml
  Makefile
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label

#913 deploy/monitoring: Stack of (speculative) changes required to get monitoring working in ROSA
  deploy/nexodus-client/overlays/dev/kustomization.yaml.sample
  deploy/nexodus-client/overlays/sample/kustomization.yaml.sample
  deploy/nexodus-monitoring/base/apiproxy-service-monitor.yaml
  deploy/nexodus-monitoring/base/apiserver-service-monitor.yaml
  deploy/nexodus-monitoring/base/grafana-dashboard.yaml
  deploy/nexodus-monitoring/base/grafana-datasource.yaml
  deploy/nexodus-monitoring/base/grafana.yaml
  deploy/nexodus-monitoring/base/jaeger.yaml
  deploy/nexodus-monitoring/base/kustomization.yaml
  deploy/nexodus-monitoring/base/prometheus-service.yaml
  deploy/nexodus-monitoring/overlays/dev/kustomization.yaml
  deploy/nexodus-monitoring/overlays/dev/prometheus-rbac.yaml
  deploy/nexodus-monitoring/overlays/dev/promtheus-ingress.yaml
  deploy/nexodus-monitoring/overlays/rosa/apiproxy-service-monitor.yaml
  deploy/nexodus-monitoring/overlays/rosa/apiserver-service-monitor.yaml
  deploy/nexodus-monitoring/overlays/rosa/kustomization.yaml
  deploy/nexodus-monitoring/overlays/rosa/prometheus-rbac.yaml
  deploy/nexodus/overlays/dev/kustomization.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
  deploy/nexodus/overlays/released/kustomization.yaml
Labels: no-design-required, no-docs-required

#917 Remove zone from the remaining docs and flags
  .gitignore
  cmd/nexd/main.go
  docs/development/design/design-discovery.md
  docs/development/design/solution-architecture.md
  docs/development/design/userspace-mode.md
  docs/development/development.md
  docs/user-guide/agent.md
  docs/user-guide/discovery-and-relay.md
  docs/user-guide/nexctl.md
  docs/user-guide/scenarios/containers-on-nodes.md
  docs/user-guide/subnet-routers.md
  internal/routers/routers.go
Labels: no-design-required, has-docs

#915 mergify: Enforce actionlint check
  .github/mergify.yml
  .github/workflows/actionlint.yml
Labels: no-design-required, no-docs-required

#918 deploy/monitoring: Fix typo
  deploy/nexodus-monitoring/overlays/dev/prometheus-ingress.yaml
Labels: no-design-required, no-docs-required

#919 deploy: Use RollingUpdate for Nexodus components
  deploy/nexodus/base/apiproxy/deployment.yaml
  deploy/nexodus/base/apiserver/deployment.yaml
  deploy/nexodus/base/frontend/deployment.yaml
Labels: no-design-required, no-docs-required

#921 rpm: Drop f37 support
  .github/workflows/deploy.yml
  Makefile
  docs/quickstart.md
  docs/user-guide/agent.md
Labels: no-design-required, has-docs

#925 docs: fix typo
  docs/user-guide/nexd-proxy.md
Labels: no-design-required, has-docs

#923 hack: Add a stun-client utility
  go.mod
  hack/stun-client/stun-client.go
Labels: no-design-required, no-docs-required

#922 mergify: Add tests checklist item via label enforcement
  .github/mergify.yml
  docs/development/pull-requests.md
Labels: no-design-required, has-docs

#920 Add http headers to debugs in the case of nexd API call failures
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required, missing-tests-label

#928 nexd: Reduce error logs
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#914 bump: required go version
  go.mod
  go.sum
Labels: no-design-required, no-docs-required, no-tests-required

#858 nexd: Add ingress UDP proxy support and IPv6 proxy support
  docs/user-guide/nexd-proxy.md
  integration-tests/proxy_test.go
  integration-tests/util_test.go
  internal/nexodus/nexodus_userspace.go
  internal/nexodus/userspace_proxy.go
  internal/nexodus/wg.go
Labels: nexd, tests, proxy, has-design, has-docs, has-tests

#935 ci: Use go 1.20 in publish-rpms
  .github/workflows/deploy.yml
Labels: no-design-required, no-docs-required, no-tests-required

#934 Makefile: Fix file permissions for gen-openapi-client
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#936 ci: Remove more steps from publish-rpms
  .github/workflows/deploy.yml
Labels: no-design-required, no-docs-required, no-tests-required

#881 nexctl: Add dynamic proxy rule management
  cmd/nexctl/connectivity.go
  cmd/nexctl/local_unix.go
  cmd/nexd/main.go
  docs/development/design/userspace-mode.md
  docs/user-guide/nexd-proxy.md
  go.mod
  go.sum
  integration-tests/proxy_test.go
  internal/nexodus/ctlserver.go
  internal/nexodus/nexodus.go
  internal/nexodus/userspace_proxy.go
Labels: has-design, has-docs, has-tests
