Repository nexodus-io/nexodus, pull requests merged in 2023-12, with the labels that each got.

#1711 Fix the timeout property in the qa-saas workflow
  .github/workflows/qa-saas.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1713 feat: add a user_identities table to track user emails
  Makefile
  cmd/nexctl/invitation.go
  integration-tests/features/invitation-api.feature
  integration-tests/util_test.go
  internal/api/public/model_models_add_invitation.go
  internal/api/public/model_models_invitation.go
  internal/database/database.go
  internal/database/migration_20231130_0000/migration.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/handlers_test.go
  internal/handlers/invitations.go
  internal/handlers/user.go
  internal/models/invitation.go
  internal/models/user_identity.go
  internal/routers/middleware.go
  ui/src/pages/Invitations.tsx
Labels: no-design-required, no-docs-required, has-tests

#1715 nexctl: reduce binary size, add yaml support, table format all list results
  cmd/nexctl/connectivity.go
  cmd/nexctl/exit_node.go
  cmd/nexctl/local_unix.go
  cmd/nexctl/main.go
  cmd/nexctl/peers.go
  docs/user-guide/nexctl.md
  go.mod
  internal/api/nexctl.go
  internal/nexodus/ctlconnectivty.go
  internal/nexodus/keepalive.go
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1717 feat: add support for sending emails from the apiserver
  .excalidraw-ignore
  Makefile
  cmd/apiserver/main.go
  go.mod
  go.sum
  internal/email/message.go
  internal/email/message_test.go
  internal/email/smtp.go
  internal/email/test.png
  internal/handlers/api.go
  internal/util/Ignore_error.go
Labels: no-design-required, no-docs-required, has-tests

#1716 Add accept invitations to the UI
  internal/api/public/model_models_user_info_response.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  pkg/oidcagent/handlers.go
  pkg/oidcagent/models/models.go
  ui/src/pages/Invitations.tsx
  ui/src/providers/AuthProvider.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1718 use aws-actions/configure-aws-credentials@v4 for qa-saas
  .github/workflows/qa-dev.yml
  .github/workflows/qa-saas.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1729 apiserver: send an invitation email when an invitation is created.
  .excalidraw-ignore
  .gitattributes
  Makefile
  deploy/nexodus/base/apiserver/deployment.yaml
  deploy/nexodus/overlays/playground/sealed-secret-smtp.yaml
  deploy/nexodus/overlays/prod/sealed-secret-smtp.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
  deploy/nexodus/overlays/qa/sealed-secret-smtp.yaml
  docs/deployment/nexodus-service.md
  go.mod
  go.sum
  internal/email/linesplitter/linesplitter.go
  internal/email/message.go
  internal/email/message_test.fixture
  internal/email/message_test.go
  internal/email/smtp.go
  internal/handlers/invitation_emails.go
  internal/handlers/invitation_emails_test.fixture
  internal/handlers/invitation_emails_test.go
  internal/handlers/invitations.go
  internal/handlers/templates/invitation.html
  internal/handlers/templates/invitation.txt
  internal/handlers/templates/nexodus.png
Labels: no-design-required, has-docs, has-tests

#1733 prep for urfave/cli/v3
  cmd/apiserver/main.go
  cmd/apiserver/pprof_disabled.go
  cmd/apiserver/pprof_enabled.go
  cmd/nexctl/connectivity.go
  cmd/nexctl/device.go
  cmd/nexctl/device_metadata.go
  cmd/nexctl/exit_node.go
  cmd/nexctl/invitation.go
  cmd/nexctl/local_unix.go
  cmd/nexctl/main.go
  cmd/nexctl/organization.go
  cmd/nexctl/peers.go
  cmd/nexctl/reg_key.go
  cmd/nexctl/security_group.go
  cmd/nexctl/user.go
  cmd/nexctl/vpc.go
  cmd/nexd/main.go
  cmd/nexd/pprof_disabled.go
  cmd/nexd/pprof_enabled.go
Labels: no-design-required, no-docs-required, no-tests-required

#1734 cli: support persistent options on global flags of the cli commands.
  cmd/apiserver/main.go
  cmd/apiserver/pprof_disabled.go
  cmd/apiserver/pprof_enabled.go
  cmd/nexctl/connectivity.go
  cmd/nexctl/device.go
  cmd/nexctl/device_metadata.go
  cmd/nexctl/exit_node.go
  cmd/nexctl/invitation.go
  cmd/nexctl/local_unix.go
  cmd/nexctl/main.go
  cmd/nexctl/organization.go
  cmd/nexctl/peers.go
  cmd/nexctl/reg_key.go
  cmd/nexctl/security_group.go
  cmd/nexctl/user.go
  cmd/nexctl/vpc.go
  cmd/nexd/flags_unix.go
  cmd/nexd/main.go
  cmd/nexd/pprof_disabled.go
  cmd/nexd/pprof_enabled.go
  docs/user-guide/nexctl.md
  docs/user-guide/nexd.md
  go.mod
  go.sum
  hack/e2e-scripts/kctool/kctool.go
  internal/nexodus/ctlstatus.go
  pkg/oidcagent/cmd/go-oidc-agent/main.go
  pkg/oidcagent/examples/apiserver/main.go
Labels: no-design-required, no-docs-required, no-tests-required

#1746 Update sealed secrets for the new Rosa cluster
  deploy/nexodus/overlays/playground/sealed-secret.yaml
  deploy/nexodus/overlays/prod/sealed-secret.yaml
  deploy/nexodus/overlays/qa/sealed-secret.yaml
  deploy/nexodus/overlays/released/auth-sealed-secret.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1747 Correctly seal the secrets for prod/qa namespaces
  deploy/nexodus/overlays/playground/sealed-secret-smtp.yaml
  deploy/nexodus/overlays/prod/sealed-secret-smtp.yaml
  deploy/nexodus/overlays/prod/sealed-secret.yaml
  deploy/nexodus/overlays/qa/sealed-secret-smtp.yaml
  deploy/nexodus/overlays/qa/sealed-secret.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1748 Upgrade the grafana api version to v1beta1
  deploy/nexodus-monitoring/base/grafana/apiserver-dashboard.yaml
  deploy/nexodus-monitoring/base/grafana/datasource.yaml
  deploy/nexodus-monitoring/base/grafana/grafana.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana-patch.yaml
  deploy/nexodus-monitoring/overlays/rosa/kustomization.yaml
  deploy/nexodus-monitoring/overlays/rosa/monitoringstack.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1750 reseal grafana secret for new cluster
  deploy/nexodus-monitoring/overlays/rosa/grafana/secret.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1751 fix for smtp-from flag
  cmd/apiserver/main.go
Labels: no-design-required, no-docs-required, no-tests-required

#1752 qa-dev tshooting of ansible unreachables
  .github/workflows/qa-dev.yml
  hack/e2e-scripts/aws-e2e-pr-build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1753 Turn up verbose logging for qa-dev
  .github/workflows/qa-dev.yml
  hack/e2e-scripts/aws-e2e-pr-build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1755 Adjust qa-saas cron job ENV values
  .github/workflows/qa-saas.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1756 Add secrets file to the terminate ansible play
  .github/workflows/qa-dev.yml
  .github/workflows/qa-saas.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1754 fix: import the user picture from the google profile
  deploy/nexodus/overlays/playground/files/nexodus.json
  deploy/nexodus/overlays/prod/files/nexodus.json
  deploy/nexodus/overlays/qa/files/nexodus.json
Labels: no-design-required, no-docs-required, no-tests-required

#1757 Adjust ansible cfg
  ops/ansible/aws/ansible.cfg
Labels: no-design-required, no-docs-required, no-tests-required

#1759 Adjust qa-saas cron time
  .github/workflows/qa-saas.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1760 Set QA secrets for cron job
  .github/workflows/qa-saas.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1790 Make longer running Ansible tasks async for an attempt at #1789
  .github/workflows/qa-dev.yml
  hack/e2e-scripts/aws-e2e-pr-build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1791 Explicitly set the python var
  hack/e2e-scripts/aws-e2e-pr-build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1779 Minor fixes in the peers ping permutations
  integration-tests/integration_test.go
Labels: no-design-required, no-docs-required, no-tests-required
