Repository nexodus-io/nexodus, pull requests merged in 2023-10, with the labels that each got.

#1483 SecGroup UI bugs fixes and improvements
  ui/src/pages/Devices.tsx
  ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
  ui/src/pages/SecurityGroups/SecurityGroupStructs.tsx
  ui/src/pages/SecurityGroups/SecurityGroupTable.tsx
  ui/src/pages/SecurityGroups/SecurityGroups.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1484 qa-dev: Collect nexd logs later in the job
  ops/ansible/aws/collect-logs/main.yml
  ops/ansible/aws/deploy-ec2.yml
  ops/ansible/aws/deploy-mesh/tasks/main.yml
  ops/ansible/aws/deploy-relay/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1485 Reset the notifcation state to have it re-render on change
  ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
  ui/src/pages/SecurityGroups/SecurityGroups.tsx
Labels: ui, has-design, has-docs, has-tests

#1498 nexd: Move some keys log msgs to debug
  internal/nexodus/keys.go
Labels: no-design-required, no-docs-required, no-tests-required

#1497 Add an accordian view to UI device listing
  ui/src/pages/Devices.tsx
Labels: ui, no-design-required, no-docs-required, no-tests-required

#1496 Add more clarity to IP Range SG labels
  ui/package.json
  ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
  ui/src/pages/SecurityGroups/SecurityGroupTable.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1472 Security group agent side rule fixes
  integration-tests/security_group_test.go
  internal/handlers/security_group.go
  internal/handlers/security_group_test.go
  internal/nexodus/policy_linux.go
  ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1501 Add UI logging for an uncaught error
  ui/src/providers/AuthProvider.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1504 rpm: don't overrwrite config on upgrade
  Makefile
  contrib/rpm/nexodus.spec.in
Labels: no-design-required, no-docs-required, no-tests-required

#1503 apiserver: add apis to manage registration tokens.
  cmd/apiserver/main.go
  deploy/nexodus/base/apiproxy/deployment.yaml
  deploy/nexodus/base/apiproxy/files/envoy.yaml
  deploy/nexodus/base/apiproxy/kustomization.yaml
  deploy/nexodus/base/apiserver/deployment.yaml
  deploy/nexodus/base/apiserver/kustomization.yaml
  docs/development/design/device-registration.md
  docs/development/design/diagrams/design-registration-d1.png
  docs/development/design/diagrams/design-registration-d2.png
  integration-tests/features/registration-token-api.feature
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_registration_token.go
  internal/api/public/client.go
  internal/api/public/model_models_add_registration_token.go
  internal/api/public/model_models_device.go
  internal/api/public/model_models_registration_token.go
  internal/database/database.go
  internal/database/migration_20231002_0000/20230801-0000.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/api.go
  internal/handlers/device.go
  internal/handlers/error.go
  internal/handlers/events.go
  internal/handlers/handlers_test.go
  internal/handlers/organization.go
  internal/handlers/registration_tokens.go
  internal/models/device.go
  internal/models/registration_token.go
  internal/routers/middleware.go
  internal/routers/routers.go
  internal/routers/token.rego
Labels: has-design, no-docs-required, has-tests

#1505 nexd: Handle invalid tokens at startup
  internal/nexodus/nexodus.go
  internal/util/retry_operation.go
Labels: no-design-required, no-docs-required, no-tests-required

#1506 Added a `make telepresensec-connect-f` target
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1431 nexd: dynamic peering
  cmd/nexctl/connectivity.go
  internal/nexodus/ctlconnectivty.go
  internal/nexodus/keepalive.go
  internal/nexodus/nexodus.go
  internal/nexodus/wg.go
  internal/nexodus/wg_peers.go
  ops/ansible/aws/validate-connectivity/tasks/main.yml
Labels: nexd, no-design-required, no-docs-required, no-tests-required

#1508 Add the default originate to advertise-cidr instead of child-prefix
  cmd/nexd/main.go
Labels: no-design-required, no-docs-required, no-tests-required

#1515 Move nexctl connection status to the last column for aligment
  cmd/nexctl/connectivity.go
Labels: no-design-required, no-docs-required, no-tests-required

#1518 Free up space to avoid runners running out of disk in e2e
  .github/workflows/build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1533 feat: link to the openapi docs from the dashboard.
  deploy/nexodus/base/apiproxy/files/envoy.yaml
  internal/routers/routers.go
  ui/src/pages/Dashboard.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1519 Runner space optimizations and cleanup
  .github/workflows/build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1521 nexd: fixes #1482 add logging to notify user when nexodus agent successfully reconcile …
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, no-tests-required

#1551 e2e: Allow for some packet drops in udp tests
  integration-tests/proxy_test.go
Labels: no-design-required, no-docs-required, has-tests

#1539 nexd: peering unit tests, round 1
  Makefile
  internal/nexodus/wg_peers.go
  internal/nexodus/wg_peers_test.go
Labels: no-design-required, no-docs-required, has-tests

#1553 nexd: Add unit tests for peering method fallback and fix some bugs
  internal/nexodus/nexodus.go
  internal/nexodus/wg_peers.go
  internal/nexodus/wg_peers_test.go
Labels: no-design-required, no-docs-required, has-tests

#1556 Exit node fixes
  internal/nexodus/ctlexit.go
  internal/nexodus/exit_origin.go
  internal/nexodus/route_darwin.go
  internal/nexodus/route_linux.go
  internal/nexodus/route_windows.go
Labels: no-design-required, no-docs-required, no-tests-required

#1538 Add registration token cli
  Makefile
  cmd/apiserver/main.go
  cmd/nexctl/invitation.go
  cmd/nexctl/main.go
  cmd/nexctl/registration_token.go
  cmd/nexd/main.go
  docs/development/design/device-registration.md
  docs/development/design/diagrams/design-registration-d2.png
  go.mod
  go.sum
  integration-tests/features/registration-token-api.feature
  integration-tests/integration_test.go
  integration-tests/steps_test.go
  internal/api/public/api_registration_token.go
  internal/api/public/model_models_registration_token.go
  internal/client/apiclient.go
  internal/client/options.go
  internal/cucumber/cucumber.go
  internal/cucumber/http_request.go
  internal/cucumber/http_response.go
  internal/cucumber/sql.go
  internal/database/database.go
  internal/database/migration_20231019_0000/20231019-0000.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/api.go
  internal/handlers/device.go
  internal/handlers/envoy_authz.go
  internal/handlers/events.go
  internal/handlers/organization.go
  internal/handlers/registration_tokens.go
  internal/models/error.go
  internal/models/registration_token.go
  internal/nexodus/nexodus.go
  internal/routers/token.rego
  internal/state/state.go
  internal/wgcrypto/wgcrypto.go
  internal/wgcrypto/wgcrypto_test.go
  ui/src/App.tsx
  ui/src/layout/Menus.tsx
  ui/src/pages/RegistrationTokens.tsx
Labels: has-design, no-docs-required, has-tests

#1552 Add PacketFilter policy support for macOS
  docs/user-guide/security-groups.md
  internal/nexodus/exit_client.go
  internal/nexodus/exit_node.go
  internal/nexodus/exit_origin.go
  internal/nexodus/net_router.go
  internal/nexodus/nexodus.go
  internal/nexodus/policy_darwin.go
  internal/nexodus/policy_darwin_test.go
  internal/nexodus/policy_linux.go
  internal/nexodus/policy_windows.go
Labels: no-design-required, has-docs, has-tests

#1555 Add qa-dev to promote for promotion validation
  .github/workflows/promote.yml
Labels: no-design-required, no-docs-required, has-tests
