Repository nexodus-io/nexodus, pull requests merged in 2023-11, with the labels that each got.

#1567 Update nexodus-io/wireguard-go dependency to latest released version
  go.mod
  go.sum
Labels: no-design-required, no-docs-required, no-tests-required

#1570 Add a dependancy on qa-dev for prod update in the promote workflow
  .github/workflows/promote.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1576 Pull and load redis image to Kind cluster
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1577 nexd: Remove --stun option
  cmd/nexd/main.go
  docs/development/design/nexodus-connectivity.md
  docs/user-guide/discovery-and-relay.md
  docs/user-guide/nexd.md
  internal/nexodus/nexodus.go
  ops/ansible/aws/deploy-relay/tasks/main.yml
  ops/ansible/aws/qa/qa-deploy-relay/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1579 e2e: Drop cloudflare endpoint from test
  integration-tests/routing_test.go
Labels: no-design-required, no-docs-required, has-tests

#1578 rpm: depend on nftables
  contrib/rpm/nexodus.spec.in
Labels: no-design-required, no-docs-required, no-tests-required

#1580 apiserver: Fix bug where security-group events were not being sent on security group updates.
  integration-tests/features/events-api.feature
  integration-tests/routing_test.go
  internal/handlers/security_group.go
Labels: no-design-required, no-docs-required, has-tests

#1581 Make the default security group id match the org id.
  internal/handlers/organization.go
  internal/handlers/security_group.go
  internal/handlers/user.go
Labels: no-design-required, no-docs-required, no-tests-required

#1583 ui: fix security groups after API changes
  ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
  ui/src/pages/SecurityGroups/SecurityGroups.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1585 Fix the float debug printing
  internal/nexodus/keepalive.go
Labels: no-design-required, no-docs-required, no-tests-required

#1584 Prune the qa-dev host on each run
  hack/e2e-scripts/aws-e2e-pr-build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1587 Fix for gosec G601 error
  internal/handlers/invitations_test.go
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1588 apiserver: add tests and fix bugs related to the new vpc resource
  integration-tests/features/organization-api.feature
  integration-tests/features/vpc-api.feature
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_vpc.go
  internal/api/public/model_models_update_vpc.go
  internal/cucumber/http_response.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/vpc.go
  internal/models/vpc.go
  internal/routers/routers.go
Labels: no-design-required, no-docs-required, has-tests

#1598 nexctl: support updating a device to change the hostname or security-group
  cmd/nexctl/device.go
  integration-tests/features/device-api.feature
  internal/api/public/model_models_update_device.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/device.go
  internal/models/device.go
Labels: has-design, no-docs-required, missing-docs-label, has-tests

#1600 nextctl: make all fields of the sg update optional.
  cmd/nexctl/security_group.go
  integration-tests/features/security-group-api.feature
  integration-tests/helper_test.go
  internal/handlers/security_group.go
  internal/handlers/security_group_test.go
  internal/models/security_group.go
  internal/util/string.go
Labels: no-design-required, no-docs-required, has-tests

#1444 nexd: fixes #1426 If your machine's time is set to 15 mins into the future, nexd will fail to login
  internal/api/public/model_models_device_start_response.go
  internal/client/apiclient.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  pkg/oidcagent/handlers.go
  pkg/oidcagent/models/models.go
Labels: no-design-required, no-docs-required, no-tests-required

#1599 Only add a fwmark if exit node is enabled
  internal/nexodus/exit_node.go
  internal/nexodus/nexodus_linux.go
  internal/nexodus/nexodus_windows.go
Labels: no-design-required, no-docs-required, no-tests-required

#1586 apiserver: implement a per user concurrency limiter
  go.mod
  go.sum
  internal/routers/concurrency_limiter.go
  internal/routers/middleware.go
Labels: no-design-required, no-docs-required, no-tests-required

#1601 Ensure CLI docs stay up to date
  Makefile
  docs/user-guide/nexctl.md
  docs/user-guide/nexd.md
  hack/nexctl-docs.sh
  hack/nexd-docs.sh
Labels: no-design-required, has-docs, has-tests

#1603 apiserver: a few small api tweaks.
  Makefile
  cmd/nexctl/invitation.go
  cmd/nexctl/local_unix.go
  cmd/nexctl/registration_token.go
  cmd/nexctl/security_group.go
  cmd/nexctl/vpc.go
  cmd/nexd/flags_unix.go
  cmd/nexd/flags_windows.go
  cmd/nexd/main.go
  docs/user-guide/nexctl.md
  docs/user-guide/nexd.md
  hack/nexd-docs.sh
  integration-tests/features/events-api.feature
  integration-tests/features/invitation-api.feature
  integration-tests/features/security-group-api.feature
  integration-tests/security_group_test.go
  internal/api/paths_darwin.go
  internal/api/paths_linux.go
  internal/api/paths_windows.go
  internal/api/public/model_models_add_reg_key.go
  internal/api/public/model_models_add_security_group.go
  internal/api/public/model_models_invitation.go
  internal/api/public/model_models_reg_key.go
  internal/api/public/model_models_security_group.go
  internal/api/public/model_models_update_security_group.go
  internal/database/database.go
  internal/database/migration_20231106_0000/20231106-0000.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/envoy_authz.go
  internal/handlers/invitations.go
  internal/handlers/reg_key.go
  internal/handlers/security_group.go
  internal/handlers/security_group_test.go
  internal/models/invitation.go
  internal/models/reg_key.go
  internal/models/security_group.go
Labels: no-design-required, no-docs-required, has-tests

#1607 fixes: #1605 Error responses have the wrong content type set
  cmd/nexctl/device.go
  cmd/nexctl/device_metadata.go
  cmd/nexctl/invitation.go
  cmd/nexctl/main.go
  cmd/nexctl/organization.go
  cmd/nexctl/reg_key.go
  cmd/nexctl/security_group.go
  cmd/nexctl/user.go
  cmd/nexctl/vpc.go
  integration-tests/features/reg-key-api.feature
  internal/cucumber/http_response.go
  internal/handlers/device.go
  internal/handlers/device_metadata.go
  internal/handlers/envoy_authz.go
  internal/handlers/events.go
  internal/handlers/handlers.go
  internal/handlers/invitations.go
  internal/handlers/organization.go
  internal/handlers/reg_key.go
  internal/handlers/security_group.go
  internal/handlers/vpc.go
  internal/models/error.go
Labels: no-design-required, no-docs-required, has-tests

#1608 Pick best host ip to get e2e working on OS X again
  Containerfile.dev
  hack/localip/main.go
  hack/stun-server/main.go
  internal/nexodus/utils.go
Labels: no-design-required, no-docs-required, no-tests-required

#1609 deps: move from my fork of github.com/mhmtszr/concurrent-swiss-map
  go.mod
  go.sum
Labels: no-design-required, no-docs-required, no-tests-required

#1610 Openapi work
  internal/cucumber/http_response.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/reg_key.go
  internal/routers/routers.go
Labels: no-design-required, no-docs-required, no-tests-required

#1611 Move default SecurityGroup from Org to VPC
  cmd/nexctl/organization.go
  cmd/nexctl/security_group.go
  cmd/nexctl/vpc.go
  integration-tests/features/events-api.feature
  integration-tests/features/organization-api.feature
  integration-tests/features/security-group-api.feature
  integration-tests/features/vpc-api.feature
  integration-tests/security_group_test.go
  internal/api/public/api_auth.go
  internal/api/public/api_reg_key.go
  internal/api/public/model_models_add_organization.go
  internal/api/public/model_models_add_security_group.go
  internal/api/public/model_models_add_vpc.go
  internal/api/public/model_models_organization.go
  internal/api/public/model_models_security_group.go
  internal/api/public/model_models_update_vpc.go
  internal/api/public/model_models_vpc.go
  internal/database/database.go
  internal/database/migration_20231107_0000/20231107-0000.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/device.go
  internal/handlers/organization.go
  internal/handlers/security_group.go
  internal/handlers/security_group_test.go
  internal/handlers/user.go
  internal/handlers/vpc.go
  internal/models/organization.go
  internal/models/security_group.go
  internal/models/vpc.go
Labels: no-design-required, has-docs, has-tests

#1615 nexctl: Fix device list --full
  cmd/nexctl/device.go
  cmd/nexctl/vpc.go
Labels: no-design-required, no-docs-required, no-tests-required

#1604 docs: Use paths for root user in help text
  cmd/nexctl/local_unix.go
  cmd/nexd/flags_unix.go
  docs/user-guide/nexctl.md
  docs/user-guide/nexd.md
Labels: no-design-required, has-docs, no-tests-required

#1616 nexd: Handle when sec group Id changes on Device
  internal/nexodus/nexodus.go
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1618 Add nexctl device list --full to e2e
  integration-tests/integration_test.go
Labels: no-design-required, no-docs-required, has-tests

#1571 nexd: Add child prefix routing through relays
  integration-tests/integration_test.go
  internal/nexodus/nexodus.go
  internal/nexodus/wg_peers.go
  internal/nexodus/wg_peers_test.go
Labels: no-design-required, no-docs-required, has-tests

#1623 Remove SG delete e2e and uncomment the still relelvant tests
  integration-tests/security_group_test.go
Labels: no-design-required, no-docs-required, has-tests

#1624 Fix the workflow name from the testing fork to upstream in promote
  .github/workflows/promote.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1626 ui: Don’t show the Users menu item.
  ui/src/App.tsx
  ui/src/layout/Menus.tsx
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1627 UI: Update SecGroups to the new VPC routers
  ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
  ui/src/pages/SecurityGroups/SecurityGroupStructs.tsx
  ui/src/pages/SecurityGroups/SecurityGroups.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1633 fixes: #1631 500 response on an invalid VPC CIDR
  cmd/nexctl/vpc.go
  integration-tests/features/vpc-api.feature
  internal/handlers/vpc.go
  internal/util/ip_utils.go
Labels: no-design-required, no-docs-required, has-tests

#1629 nexd: reuse the wireguard listen port on restart
  internal/nexodus/dump.go
  internal/nexodus/nexodus.go
  internal/nexodus/wg.go
  internal/state/state.go
Labels: no-design-required, no-docs-required, no-tests-required

#1634 Check for existing nexd process on macOS
  internal/nexodus/ctlstatus.go
Labels: no-design-required, no-docs-required, no-tests-required

#1637 feat: initial spike of importing coredns for dns server capabilities.
  go.mod
  go.sum
  internal/dnsserver/dnsserver.go
  internal/dnsserver/dnsserver_test.go
Labels: no-design-required, no-docs-required, has-tests

#1632 nexd: Don't assign tunnel IP if it conflicts with host
  integration-tests/integration_test.go
  internal/nexodus/nexodus.go
  internal/nexodus/wg_deploy.go
Labels: no-design-required, no-docs-required, has-tests

#1641 cleanup: drop the unused users security_group_id db field
  internal/database/database.go
  internal/database/migration_20231112_0000/20231112-0000.go
  internal/models/user.go
Labels: no-design-required, no-docs-required, no-tests-required

#1654 clean up: use the same default sock path on linux and osx.
  docs/user-guide/nexctl.md
  docs/user-guide/nexd.md
  internal/api/paths_linux.go
  internal/api/paths_unix.go
Labels: no-design-required, no-docs-required, has-tests

#1638 fixes #1514 - When a device is deleted it is marked deleted but still has a unique key in the device table.
  integration-tests/features/device-api.feature
  internal/api/public/api_vpc_devices_custom.go
  internal/handlers/device.go
  internal/nexodus/wg.go
Labels: no-design-required, no-docs-required, no-tests-required

#1655 Replace the curl e2e in exit node for tshooting
  integration-tests/routing_test.go
Labels: no-design-required, no-docs-required, has-tests

#1657 build: lock in container image versions to get more consistent builds
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1659 rpm: Rename russellb/nexodus to nexodus/nexodus
  .github/workflows/deploy.yml
  Makefile
  docs/quickstart.md
  docs/user-guide/agent.md
Labels: no-design-required, has-docs, no-tests-required

#1612 ci: store the previous prod tag as prod-previous so that we can
  .github/workflows/promote.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1660 Fix: the qa cert issuer.
  deploy/nexodus/overlays/openshift/kustomization.yaml
Labels: missing-docs-label, missing-design-label, missing-tests-label

#1663 fix: admin login was not working.
  integration-tests/integration_test.go
  internal/handlers/user.go
Labels: no-design-required, no-docs-required, has-tests

#1620 feat: add an initial spike of playwright UI tests
  .dockerignore
  .github/workflows/build.yml
  Containerfile.playwright
  Makefile
  hack/update-ca.sh
  integration-tests/features/webui.feature
  integration-tests/features_test.go
  integration-tests/steps_test.go
  internal/cucumber/cucumber.go
  ui/.gitignore
  ui/package-lock.json
  ui/package.json
  ui/playwright.config.ts
  ui/tests-examples/demo-todo-app.spec.ts
  ui/tests-examples/example.spec.ts
  ui/tests/env.ts
  ui/tests/login.spec.ts
Labels: no-design-required, no-docs-required, has-tests

#1658 apiserver: introduce a new private api to fully delete soft deleted records
  Makefile
  deploy/nexodus/base/apiserver/cronjob.yaml
  deploy/nexodus/base/apiserver/deployment.yaml
  deploy/nexodus/base/apiserver/kustomization.yaml
  integration-tests/features/private-api-not_parallel.feature
  integration-tests/features_test.go
  integration-tests/helper_test.go
  integration-tests/steps_test.go
  internal/cucumber/http_request.go
  internal/docs-private/docs.go
  internal/docs-private/swagger.json
  internal/docs-private/swagger.yaml
  internal/handlers/gc.go
  internal/handlers/health.go
  internal/routers/routers.go
Labels: no-design-required, no-docs-required, has-tests

#1679 nexctl: clean up api access commands to be simpler and more consistent.
  cmd/nexctl/device.go
  cmd/nexctl/device_metadata.go
  cmd/nexctl/exit_node.go
  cmd/nexctl/invitation.go
  cmd/nexctl/main.go
  cmd/nexctl/organization.go
  cmd/nexctl/peers.go
  cmd/nexctl/reg_key.go
  cmd/nexctl/security_group.go
  cmd/nexctl/user.go
  cmd/nexctl/vpc.go
Labels: no-design-required, no-docs-required, no-tests-required

#1681 rpm: Enable Fedora 39 builds
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1683 fix: deployment configs to point at the right API URL.
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1684 apiproxy: produce json error when JWT validation fails.
  deploy/nexodus/base/apiproxy/files/envoy.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1687 ci: only keep track of release commits in the target tag.
  .github/workflows/deploy.yml
Labels: missing-docs-label, missing-design-label, missing-tests-label

#1682 feat: add settings field to reg-key, ux now displays the cli flag needed to start nexd wit a reg key.
  cmd/nexctl/main.go
  cmd/nexctl/reg_key.go
  cmd/nexd/main.go
  deploy/nexodus/overlays/playground/files/limits.yaml
  deploy/nexodus/overlays/playground/files/promtail.yaml
  deploy/nexodus/overlays/playground/issuer.yaml
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/playground/serviceaccount.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
  hack/update-ca.sh
  integration-tests/features/reg-key-api.feature
  internal/api/public/model_models_add_reg_key.go
  internal/api/public/model_models_reg_key.go
  internal/api/public/model_models_update_reg_key.go
  internal/database/database.go
  internal/database/migration_20231031_0000/migration.go
  internal/database/migration_20231106_0000/migratino.go
  internal/database/migration_20231107_0000/migration.go
  internal/database/migration_20231108_0000/migration.go
  internal/database/migration_20231112_0000/migration.go
  internal/database/migration_20231113_0000/migration.go
  internal/database/migration_20231114_0000/migration.go
  internal/database/migration_20231120_0000/migration.go
  internal/database/migrations/migrations.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/device.go
  internal/handlers/reg_key.go
  internal/handlers/vpc.go
  internal/models/reg_key.go
  ui/src/pages/JsonField.jsx
  ui/src/pages/JsonInput.jsx
  ui/src/pages/RegKeys.tsx
Labels: no-design-required, no-docs-required, has-tests

#1704 hack: adding script that backs up the sql dbs.
  hack/backup.sh
Labels: no-design-required, no-docs-required, no-tests-required

#1665 Add validation for qa/prod
  .github/workflows/qa-saas.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1708 Fix order of operations in qa-saas
  .github/workflows/qa-saas.yml
Labels: bug, no-design-required, no-docs-required, no-tests-required

#1710 ui: Color the online status icon
  ui/src/pages/Devices.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1707 Add the PPA/deb build dispatch to the deploy workflow
  .github/workflows/deploy.yml
Labels: no-design-required, no-docs-required, no-tests-required
