Repository nexodus-io/nexodus, pull requests merged in 2024-01, with the labels that each got.

#1776 Add missing prop to MenuItemLink after react-admin bump
  ui/package-lock.json
  ui/package.json
  ui/src/layout/Menus.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1801 Remove the package-lock from the root dir
  package-lock.json
Labels: no-design-required, no-docs-required, no-tests-required

#1802 Replace deprecated testcontainer apis
  go.mod
  go.sum
  integration-tests/helper_test.go
  integration-tests/routing_test.go
  integration-tests/steps_test.go
Labels: no-design-required, no-docs-required, no-tests-required

#1568 Update relay status if device rejoins as a relay
  integration-tests/features/device-api.feature
  internal/api/public/model_models_update_device.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/device.go
  internal/models/device.go
  internal/nexodus/join.go
Labels: no-design-required, no-docs-required, no-tests-required

#1818 Remove placeholder from menus.tsx to bump react-admin
  Containerfile.playwright
  ui/package-lock.json
  ui/package.json
  ui/src/App.tsx
  ui/src/layout/AppBar.tsx
  ui/src/layout/Menus.tsx
  ui/src/pages/Dashboard.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1831 Bump url-fave
  docs/user-guide/nexd.md
  go.mod
  go.sum
Labels: no-design-required, no-docs-required, no-tests-required

#1778 Added support for Derp based relay
  .github/actions/setup-go-env/action.yaml
  .github/workflows/build.yml
  .golangci.yaml
  .vscode/settings.json
  Containerfile.nexd
  Makefile
  cmd/nexd/main.go
  contrib/rpm/nexodus.spec.in
  docs/user-guide/nexd.md
  docs/user-guide/relay-nodes.md
  go.mod
  go.sum
  hack/nexd-docs.sh
  hack/relayderp-certs.sh
  integration-tests/helper_test.go
  integration-tests/relayderp_test.go
  internal/nexodus/bootstrap_dns.go
  internal/nexodus/bootstrap_dns_test.go
  internal/nexodus/cert.go
  internal/nexodus/derp.go
  internal/nexodus/derp/derp.go
  internal/nexodus/derp/derp_client.go
  internal/nexodus/derp/derp_server.go
  internal/nexodus/derp/derp_server_default.go
  internal/nexodus/derp/derp_server_linux.go
  internal/nexodus/derp/derp_test.go
  internal/nexodus/derp/derphttp/derphttp_client.go
  internal/nexodus/derp/derphttp/derphttp_server.go
  internal/nexodus/derp/derphttp/derphttp_test.go
  internal/nexodus/derp/derphttp/mesh_client.go
  internal/nexodus/derp/derphttp/websocket.go
  internal/nexodus/derp/dropreason_string.go
  internal/nexodus/derp/testdata/example_ss.txt
  internal/nexodus/derper.go
  internal/nexodus/derper_test.go
  internal/nexodus/join.go
  internal/nexodus/keys.go
  internal/nexodus/mesh.go
  internal/nexodus/nexodus.go
  internal/nexodus/nexodus_darwin.go
  internal/nexodus/nexodus_linux.go
  internal/nexodus/nexodus_windows.go
  internal/nexodus/utils.go
  internal/nexodus/websocket.go
  internal/nexodus/wg_deploy.go
  internal/nexodus/wg_derp_proxy.go
  internal/nexodus/wg_peers.go
  internal/nexodus/wg_peers_derp_mapping.go
  internal/nexodus/wg_peers_test.go
  internal/routers/token.rego
Labels: no-design-required, has-docs, has-tests

#1838 Fixes #1837 - Device online status was not being properly updated.
  internal/handlers/online_tracker.go
Labels: no-design-required, no-docs-required, no-tests-required

#1841 Moved derp server code under pkg directory
  .golangci.yaml
  internal/nexodus/derp.go
  pkg/derp/derp.go
  pkg/derp/derp_client.go
  pkg/derp/derp_server.go
  pkg/derp/derp_server_default.go
  pkg/derp/derp_server_linux.go
  pkg/derp/derp_test.go
  pkg/derp/derphttp/derphttp_client.go
  pkg/derp/derphttp/derphttp_server.go
  pkg/derp/derphttp/derphttp_test.go
  pkg/derp/derphttp/mesh_client.go
  pkg/derp/derphttp/websocket.go
  pkg/derp/dropreason_string.go
  pkg/derp/testdata/example_ss.txt
Labels: no-design-required, no-docs-required, no-tests-required

#1775 Bump and sync CI artifact up/down versions
  .github/workflows/build.yml
  .github/workflows/promote.yml
  .github/workflows/qa-dev.yml
  .github/workflows/qa-saas.yml
  .github/workflows/qa-scale-containers.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1854 ui: don’t show security group fields when that feature flag is off
  .github/workflows/deploy.yml
  deploy/nexodus/base/apiserver/kustomization.yaml
  deploy/nexodus/overlays/dev/kustomization.yaml
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/kustomization.yaml
  ui/src/App.tsx
  ui/src/common/FlagsContext.tsx
  ui/src/layout/Layout.tsx
  ui/src/layout/Menus.tsx
  ui/src/pages/Devices.tsx
  ui/src/pages/RegKeys.tsx
  ui/src/pages/VPCs.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1855 nexctl: Don't use spinner for parseable output
  cmd/nexctl/connectivity.go
Labels: no-design-required, no-docs-required, no-tests-required

#1856 Don't restrict google logins to redhat.com email addresses
  internal/routers/token.rego
Labels: no-design-required, no-docs-required, missing-docs-label, missing-design-label, no-tests-required, missing-tests-label

#1857 docs: Fix a rendering error
  docs/development/design/stack.md
Labels: no-design-required, has-docs, no-tests-required

#1858 docs: Add a link to the red hat privacy policy
  docs/policies.md
Labels: no-design-required, has-docs, no-tests-required

#1860 Resolve artifact@v4 issue
  .github/workflows/promote.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1861 Add a github token env to promote
  .github/workflows/promote.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1862 Add a token for checkout@v4
  .github/workflows/promote.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1819 Scale testing results documentation
  docs/development/scale-testing.md
Labels: no-design-required, has-docs, no-tests-required

#1840 Added design document for DERP relay integration
  docs/development/design/derp-relay.md
  docs/user-guide/nexd.md
Labels: has-design, has-docs, no-tests-required

#1874 doc: Add some more developer docs
  docs/development/code-organization.md
  docs/development/index.md
Labels: no-design-required, has-docs, no-tests-required

#1875 Run make cacerts in derpcerts Makefule section if .certs is not present
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required
