Repository nexodus-io/nexodus, pull requests merged in 2024-02, with the labels that each got.

#1877 fix: disable the sites feature flag in prod.
  deploy/nexodus/overlays/prod/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1878 Fix: enabled the smtp server access in playground and prod deployments.
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/prod/kustomization.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1839 Add e2e for online status
  integration-tests/integration_test.go
Labels: no-design-required, no-docs-required, no-tests-required

#1880 Skip tls verification for qa/dev automation
  ops/ansible/aws/aws-apex-start.yml
  ops/ansible/aws/aws-apex-stop.yml
  ops/ansible/aws/deploy-mesh/tasks/main.yml
  ops/ansible/aws/deploy-relay/tasks/main.yml
  ops/ansible/aws/qa/qa-containers-deploy-mesh/tasks/main.yml
  ops/ansible/aws/qa/qa-deploy-mesh/tasks/main.yml
  ops/ansible/aws/qa/qa-deploy-relay/tasks/main.yml
  ops/ansible/aws/start-apex-agent/tasks/main.yml
  ops/ansible/aws/stop-apex-agent/tasks/main.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1881 Redeploy the cluster between qa-dev runs
  hack/e2e-scripts/aws-e2e-pr-build.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1882 qa-dev tweaks
  hack/e2e-scripts/aws-e2e-pr-build.yml
Labels: missing-docs-label, missing-design-label, missing-tests-label

#1896 Reduce dependabot PR churn
  .github/dependabot.yml
Labels: no-design-required, no-docs-required, no-tests-required

#1902 DERP docs
  docs/user-guide/relay-nodes.md
Labels: no-design-required, has-docs, no-tests-required

#1907 Remove vscode devcontainer
  .devcontainer/devcontainer.json
  .dockerignore
  Makefile
  docs/development/tooling.md
Labels: no-design-required, no-docs-required, no-tests-required

#1913 certmode supports letsencrypt as a default value
  cmd/nexd/main.go
Labels: no-design-required, no-docs-required, no-tests-required

#1909 Fixed some logging types
  internal/nexodus/wg_derp_proxy.go
Labels: no-design-required, no-docs-required, no-tests-required

#1915 Enable IP v6 for relay integration tests
  integration-tests/relayderp_test.go
Labels: no-design-required, no-docs-required, no-tests-required

#1916 frontend: Redirect to the authorization server from the apiserver
  cmd/apiserver/main.go
  deploy/nexodus/base/apiserver/deployment.yaml
  deploy/nexodus/base/apiserver/kustomization.yaml
  deploy/nexodus/base/auth/deployment.yaml
  deploy/nexodus/base/auth/files/nexodus.json
  deploy/nexodus/base/auth/kustomization.yaml
  deploy/nexodus/overlays/playground/files/nexodus.json
  deploy/nexodus/overlays/playground/kustomization.yaml
  deploy/nexodus/overlays/prod/files/nexodus.json
  deploy/nexodus/overlays/prod/kustomization.yaml
  deploy/nexodus/overlays/qa/files/nexodus.json
  deploy/nexodus/overlays/qa/kustomization.yaml
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_auth.go
  internal/api/public/model_models_login_end_request.go
  internal/api/public/model_models_login_end_response.go
  internal/api/public/model_models_login_start_response.go
  internal/api/public/model_models_logout_response.go
  internal/api/public/model_models_refresh_token_request.go
  internal/api/public/model_models_refresh_token_response.go
  internal/api/public/model_models_update_device.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/routers/routers.go
  pkg/oidcagent/agent.go
  pkg/oidcagent/agent_test.go
  pkg/oidcagent/handlers.go
  pkg/oidcagent/handlers_test.go
  pkg/oidcagent/middleware.go
  pkg/oidcagent/models/models.go
  pkg/oidcagent/router.go
  ui/src/providers/AuthProvider.tsx
  ui/src/providers/AuthTypes.ts
  ui/src/providers/RefreshManager.ts
Labels: no-design-required, no-docs-required, no-tests-required

#1917 fix: disable caching of API responses.
  internal/routers/middleware.go
  internal/routers/routers.go
Labels: no-design-required, no-docs-required, no-tests-required

#1918 frontend: optimize the cache settings so that the assets are aggressively cached.
  ui/nginx.conf
Labels: no-design-required, no-docs-required, no-tests-required

#1924 frontend: redirect back to original window URL after login.
  pkg/oidcagent/handlers.go
  ui/src/providers/AuthProvider.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1925 go.mod: Depend on txeh 1.5.4
  go.mod
  go.sum
Labels: no-design-required, no-docs-required, no-tests-required

#1926 apiserver: fix accept link in the invitation email.
  cmd/apiserver/main.go
  internal/handlers/api.go
  internal/handlers/invitation_emails.go
  internal/handlers/invitation_emails_test.go
  pkg/oidcagent/handlers.go
Labels: no-design-required, no-docs-required, no-tests-required

#1928 docs: Add apiserver to the code organization doc
  docs/development/code-organization.md
Labels: no-design-required, has-docs, no-tests-required

#1927 Dependency bumps
  cmd/apiserver/main.go
  go.mod
  go.sum
  integration-tests/redis_fetch_manager_test.go
  internal/handlers/fetchmgr/envfm/envfm.go
  internal/handlers/handlers_test.go
  internal/handlers/online_tracker.go
Labels: no-design-required, no-docs-required, no-tests-required

#1933 apiserver/nexctl: added api and cli command to manage org memebership
  cmd/nexctl/main.go
  cmd/nexctl/organization.go
  docs/user-guide/nexctl.md
  integration-tests/features/user-organization-api.feature
  internal/api/public/.openapi-generator/FILES
  internal/api/public/api_organizations.go
  internal/api/public/model_models_user_organization.go
  internal/api/public/model_models_validation_error.go
  internal/docs-private/docs.go
  internal/docs-private/swagger.json
  internal/docs-private/swagger.yaml
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/user_organization.go
  internal/models/error.go
  internal/models/user_organization.go
  internal/routers/routers.go
Labels: no-design-required, has-docs, has-tests

#1934 apiserver: remove leftover debug logging.
  internal/handlers/user.go
  internal/ipam/ipam.go
  internal/signalbus/pg_signalbus.go
Labels: no-design-required, no-docs-required, no-tests-required

#1937 ui: Disable react-admin telemetry
  ui/src/App.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1938 Use latest OLM - v0.27.0
  Makefile
Labels: no-design-required, no-docs-required, no-tests-required

#1936 frontend: show org membership when you view an org’s details
  ui/src/DataProvider.tsx
  ui/src/pages/Organizations.tsx
  ui/src/pages/UserOrganizations.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1939 apiserver: support multiple Organization owners
  cmd/nexctl/invitation.go
  integration-tests/features/invitation-api.feature
  integration-tests/features/organization-api.feature
  integration-tests/features/user-organization-api.feature
  internal/api/public/model_models_add_invitation.go
  internal/api/public/model_models_invitation.go
  internal/api/public/model_models_organization.go
  internal/api/public/model_models_user_organization.go
  internal/database/database.go
  internal/database/datatype/string_array.go
  internal/database/migration_20240221_0000/migration.go
  internal/database/migrations/migrations.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/invitations.go
  internal/handlers/organization.go
  internal/handlers/security_group.go
  internal/handlers/user.go
  internal/handlers/vpc.go
  internal/models/base.go
  internal/models/invitation.go
  internal/models/organization.go
  internal/models/user_organization.go
  internal/util/string.go
  ui/src/components/StringListField.tsx
  ui/src/pages/Invitations.tsx
  ui/src/pages/Organizations.tsx
Labels: no-design-required, no-docs-required, has-tests

#1940 fix frontend: invitation create org pick list was empty.
  internal/handlers/handlers.go
  internal/handlers/invitations.go
  internal/handlers/organization.go
  internal/handlers/security_group.go
  internal/handlers/vpc.go
  internal/models/error.go
  ui/src/pages/Invitations.tsx
  ui/src/pages/UserOrganizations.tsx
  ui/src/pages/Users.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1935 apiserver: on org member removal, cascade delete his org resources.
  internal/handlers/user_organization.go
Labels: no-design-required, no-docs-required, no-tests-required

#1943 deploy: Request 1 GB for postgres
  deploy/nexodus/base/database/postgres.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1947 apiserver: fix reg-keys api to use new org ownership roles
  integration-tests/features/reg-key-api.feature
  internal/handlers/reg_key.go
Labels: no-design-required, no-docs-required, has-tests

#1945 Increase the timeout in DNS unit tests
  internal/dnsserver/dnsserver_test.go
Labels: no-design-required, no-docs-required, no-tests-required

#1930 frontend: fix invitation accept, we redirect to show your orgs after the invitation is accepted.
  ui/src/common/Api.tsx
  ui/src/pages/Invitations.tsx
Labels: no-design-required, no-docs-required, no-tests-required
