Repository nexodus-io/nexodus, pull requests merged in 2024-03, with the labels that each got.

#1953 nexctl: add symmetric nat to full device list output
  cmd/nexctl/device.go
Labels: no-design-required, no-docs-required, no-tests-required

#1955 Show SymmetricNAT status in the device details page
  ui/src/pages/Devices.tsx
Labels: no-design-required, no-docs-required, no-tests-required

#1959 apiserver: logged ip address now show client address instead of the a…
  deploy/nexodus/base/apiproxy/files/envoy.yaml
  internal/routers/routers.go
Labels: no-design-required, no-docs-required, no-tests-required

#1960 apiserver/nexd: improve the meta data event apis so that we can use
  cmd/nexctl/device_metadata.go
  internal/client/api_vpc.go
  internal/client/custom_informer.go
  internal/client/custom_service_network_sites.go
  internal/client/custom_vpc_device_metadata.go
  internal/client/custom_vpc_devices.go
  internal/client/custom_vpc_security_group.go
  internal/docs/docs.go
  internal/docs/swagger.json
  internal/docs/swagger.yaml
  internal/handlers/device.go
  internal/handlers/device_metadata.go
  internal/handlers/events.go
  internal/handlers/fetchmgr/memfm/mem_fetch_manager.go
  internal/handlers/fetchmgr/redisfm/redis_fetch_manager.go
  internal/handlers/fetchmgr/resource.go
  internal/handlers/fetchmgr/tests/fetchmgr.go
  internal/handlers/security_group.go
  internal/handlers/service_network.go
  internal/handlers/site.go
  internal/handlers/vpc.go
  internal/nexodus/join.go
  internal/nexodus/nexodus.go
  internal/util/json.go
Labels: no-design-required, no-docs-required, has-tests

#1961 deployment: attempt to fix the nexodus monitoring stack on qa/prod
  deploy/nexodus-monitoring/overlays/rosa/monitoringstack.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1963 deployment: fix grafana host name
  deploy/nexodus-monitoring/overlays/rosa/grafana-patch.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/route.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1964 Revert "deployment: fix grafana host name "
  deploy/nexodus-monitoring/overlays/rosa/grafana-patch.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/route.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1965 deployment: use ‘apiVersion’ supported on our cluster.
  deploy/nexodus-monitoring/base/grafana/apiserver-dashboard.yaml
  deploy/nexodus-monitoring/base/grafana/datasource.yaml
  deploy/nexodus-monitoring/base/grafana/grafana.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1966 deploy: fix GrafanaDatasource kind name
  deploy/nexodus-monitoring/base/grafana/datasource.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1967 grafana: update CRDs to new version structure.
  deploy/nexodus-monitoring/base/grafana/apiserver-dashboard.yaml
  deploy/nexodus-monitoring/base/grafana/grafana.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1968 grafana: convert the datasources to the new CRD version.
  deploy/nexodus-monitoring/base/grafana/datasource.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1969 Grafana: remove field that is causing argo to go out of sync.
  deploy/nexodus-monitoring/base/grafana/datasource.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1970 grafana: another attempt to fix the route host name.
  deploy/nexodus-monitoring/overlays/rosa/grafana-patch.yaml
  deploy/nexodus-monitoring/overlays/rosa/grafana/route.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1971 fix: grafana service name changed
  deploy/nexodus-monitoring/overlays/rosa/grafana/route.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1972 Grafana: fix service settings.
  deploy/nexodus-monitoring/overlays/rosa/grafana/route.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1974 monitoring: fix `make deploy-monitoring-stack` so it works again.
  deploy/nexodus-monitoring/base/grafana/grafana.yaml
  deploy/nexodus-monitoring/overlays/dev/ingress.yaml
  deploy/nexodus-monitoring/overlays/dev/kustomization.yaml
  deploy/operators/base/grafana.yaml
Labels: no-design-required, no-docs-required, no-tests-required

#1984 cleanup: drop derp fork if it’s not needed.
  go.mod
  internal/nexodus/derp.go
  pkg/derp/derp.go
  pkg/derp/derp_client.go
  pkg/derp/derp_server.go
  pkg/derp/derp_server_default.go
  pkg/derp/derp_server_linux.go
  pkg/derp/derp_test.go
  pkg/derp/derphttp/derphttp_client.go
  pkg/derp/derphttp/derphttp_server.go
  pkg/derp/derphttp/derphttp_test.go
  pkg/derp/derphttp/mesh_client.go
  pkg/derp/derphttp/websocket.go
  pkg/derp/dropreason_string.go
  pkg/derp/testdata/example_ss.txt
Labels: no-design-required, no-docs-required, no-tests-required

#1944 Playwright bump
  Containerfile.playwright
  ui/package-lock.json
  ui/package.json
Labels: no-design-required, no-docs-required, has-tests

#1989 upgrade to go 1.22
  .github/actions/setup-go-env/action.yaml
  Containerfile.apiserver
  Containerfile.dev
  Containerfile.ipam
  Containerfile.nexd
  Containerfile.test
  contrib/rpm/nexodus.spec.in
  go.mod
Labels: missing-docs-label, missing-design-label, missing-tests-label

#1979 Fixes e2e failures on mac
  Makefile
  go.mod
  go.sum
  integration-tests/helper_test.go
  integration-tests/relayderp_test.go
  internal/nexodus/derp.go
  internal/nexodus/in_mem_resolver.go
  internal/nexodus/nexodus.go
  internal/nexodus/nexodus_darwin.go
  internal/nexodus/utils.go
  internal/nexodus/wg_derp_proxy.go
  internal/nexodus/wg_peers.go
  internal/nexodus/wg_peers_test.go
Labels: no-design-required, no-docs-required, has-tests

#1992 Lets make sure we rev the gh actions cache on a go version change.
  .github/actions/setup-go-env/action.yaml
Labels: missing-docs-label, missing-design-label, missing-tests-label

#1995 fix: build is broken after go 1.22 upgrade, it needs new golangci-lint installed.
  cmd/apiserver/main.go
  cmd/nexctl/main.go
  hack/install-tools.sh
  internal/nexodus/nexodus.go
  pkg/oidcagent/agent.go
  pkg/oidcagent/handlers.go
Labels: missing-docs-label, missing-design-label, missing-tests-label

#1994 ci: Stop publishing rpms to the deprecated copr repo
  .github/workflows/deploy.yml
Labels: no-design-required, no-docs-required, no-tests-required
